### PR TITLE
removed ARM toolchain dependency from alire.toml

### PR DESCRIPTION
**Pull request by hgrodriguez**
This PR resolves the comment from @Fabien-Chouteau :  
https://github.com/alire-project/alire-index/pull/516#discussion_r874711259

### CODE REVIEW

**Comment by mosteo** [comment]
I'm out of my depth here. @Fabien-Chouteau , if a crate doesn't depend on a cross-compiler, can it still specify a runtime and/or target in its gpr file?

**Comment by hgrodriguez** [comment]
ok I removed the dependency on the runtime and target in EEPROM_i2c.grp. please ignore this PR I will raise another one for the update. Sorry for time wasted here on your both sides.

**Comment by Fabien-Chouteau** [comment]
Indeed the library should not specify target nor run-time, this will be set by the application that with's the library.

**Comment by hgrodriguez** [comment]
> Indeed the library should not specify target nor run-time, this will be set by the application that with's the library.

I will remove this and raise another PR, please reject/close this PR. @Fabien-Chouteau I appreciate your input and will change this accordingly, this is the first time that I had to learn how this works, i will implement this from now onwards as requested here.

**Comment by Fabien-Chouteau** [comment]
Probably something we should document under a "Portable Libraries" section...

**Comment by hgrodriguez** [comment]
> Probably something we should document under a "Portable Libraries" section...

👍

**Comment by hgrodriguez** [comment]
can I close the pull request myself to start over and have a fresh beginning?

**Comment by mosteo** [comment]
I'm cloisng this one now, but yes, @hgrodriguez, you can close any PR you open.

**Pull request closed without merging**
