### PR TITLE
Update VSS version

### PR DESCRIPTION
**Pull request by reznikmm**
This version includes grapheme clusters iterators and many more improvements.

### CODE REVIEW

**Comment by reznikmm** [comment]
I've put compiler restriction in the crate, but CI still fails on old compiler. Any advice?

```
[[depends-on]]
gnat = ">=2020|(>=10 & <=2000)"
```

**Comment by mosteo** [comment]
Well, it seems that gnat 10 is also unable to compile that. You might try upping the lower bound to 11? Which compiler are you working with?

**Comment by reznikmm** [comment]
> Well, it seems that gnat 10 is also unable to compile that. You might try upping the lower bound to 11? Which compiler are you working with?

Indeed, GCC 10 lacks String_Literal indeed. I've updated crate constraint to GCC 11.

Thank you!

**Comment by mosteo** [comment]
The current failure is my fault. Will fix shortly.

**Comment by mosteo** [comment]
@reznikmm , if you rebase on top of `devel-1.1` again, we should see the result of your last change.

**Review by mosteo — APPROVED** [review]

**Pull request merged**
