### PR TITLE
mold latest version

### PR DESCRIPTION
**Pull request by rocher**
### New crate mold

Mold —•— _Meta-variable Operations for Lean Development_ —•—

### CODE REVIEW

**Comment by rocher** [comment]
Don't understand why it fails with:
```txt
clic-user_input.adb:265:31: error: literal out of range of type Standard.Character
clic-tty.ads:101:19: error: literal out of range of type Standard.Character
clic-tty.ads:106:17: error: literal out of range of type Standard.Character
clic-command_line.adb:2244:40: warning: aspect Unreferenced specified for "Success" [enabled by default]
clic-command_line.adb:2461:71: warning: aspect Unreferenced specified for "Success" [enabled by default]

   compilation of clic-user_input.adb failed
```

Any idea or suggestion?

**Comment by rocher** [comment]
Don't understand why it fails with:
```txt
clic-user_input.adb:265:31: error: literal out of range of type Standard.Character
clic-tty.ads:101:19: error: literal out of range of type Standard.Character
clic-tty.ads:106:17: error: literal out of range of type Standard.Character
clic-command_line.adb:2244:40: warning: aspect Unreferenced specified for "Success" [enabled by default]
clic-command_line.adb:2461:71: warning: aspect Unreferenced specified for "Success" [enabled by default]

   compilation of clic-user_input.adb failed
```

Any idea or suggestion?

**Comment by mosteo** [comment]
Arg. Being only in the dev branches, this has been likely introduced recently, I think I know where. I'm on it.

**Comment by mosteo** [comment]
Alright, this is not a new problem. The problem is that the clic version that is indexed is not yet updated to build in full Unicode mode, which `alr 2.0` enables by default. I'll make a `clic=0.3` release and you'll need to update your dependency to `clic="~0.3"`. I'll ping you then.

**Review by mosteo — APPROVED** [review]

**Comment by mosteo** [comment]
@Fabien-Chouteau it seems this one could serve to have more specialized templates in `alr init`?

**Pull request merged**
