### PR TITLE
Add Libadalang & Langkit_Support 21.0.0

### PR DESCRIPTION
**Pull request by pmderodat**

### CODE REVIEW

**Comment by pmderodat** [comment]
Hello,

FYI, there is a bug between GPRbuild and GCC that appears when GCC is configured to automatically pass `-pie` to the linker (which is the case for at least Debian’s, Ubuntu’s and ArchLinux’s GCC). When building standalone static libraries (and thus when building LAL and Langkit_Support), GPRbuild does a partial link (`-r`), which conflicts with `-pie`:

```
/usr/bin/ld: -r and -pie may not be used together
```

Both crates are fully functional with GNAT Community (as there’s no automatic `-pie`), and it can still be used in a restricted way with the problematic GCC builds: just pass `-XLIBRARY_TYPE=relocatable` to `alr build`.

Any advice as what I should do as far as Alire is concerned?

**Comment by mosteo** [comment]
I guess this `-XLIBRARY_TYPE=relocatable` is not for LAL or langkit? So it cannot be made the default.

One solution is to add:
```
[gpr-set-externals."case(toolchain)".system]
LIBRARY_TYPE = "relocatable"
```
which will define the variable for the packaged compilers in debian/ubuntu, but not for the CE ones. (Arch, being unknown to `alr`, would also not get it.)

Alternatively, it could be always defined, but then we don't have yet a way to override the setting.

**Comment by mosteo** [comment]
~I guess that with the conditional, the build will fail on centos. Uhm...~ No, because on CentOS the compiler is the CE one.

**Comment by pmderodat** [comment]
Thanks for the suggestion! It seems to work, so let’s start with that.

For the record, when I add this `gpr-set-externals` tuning to both crates, I’m getting an error while trying to build:
```
$ alr with libadalang
$ alr build
error: Trying to set an alredy defined environment variable: LIBRARY_TYPE is already defined as relocatable
```

Not sure if this is a bug, but it clearly surprised me: both definitions use the same value, and passing `-XLIBRARY_TYPE=static` when one crate sets it to `relocatable` works fine. Anyway, I’ll amend the Langkit_Support crate only.

**Comment by Fabien-Chouteau** [comment]
> For the record, when I add this `gpr-set-externals` tuning to both crates, I’m getting an error while trying to build:
> 
> ```
> $ alr with libadalang
> $ alr build
> error: Trying to set an alredy defined environment variable: LIBRARY_TYPE is already defined as relocatable
> ```

Can you try with:
```
$ alr -vv -d build
```

**Comment by pmderodat** [comment]
I misread my logs: it’s actually the `alr with libadalang` command that fails! Adding `-vv -d` adds tons of logs, but I guess the end of the output will help:
```
detail: Env: langkit_support (gpr ext) sets 'relocatable' to 'LIBRARY_TYPE'
detail: Env: libadalang (gpr ext) sets 'relocatable' to 'LIBRARY_TYPE'
stderr: Trying to set an alredy defined environment variable: LIBRARY_TYPE is already defined as relocatable
error: Trying to set an alredy defined environment variable: LIBRARY_TYPE is already defined as relocatable
debug: ---8<--- Exception dump begin ---8<---
debug: ALIRE.CHECKED_ERROR
debug: Trying to set an alredy defined environment variable: LIBRARY_TYPE is already defined as relocatable
debug: raised ALIRE.CHECKED_ERROR : alire-stored-error:1
[/home/pmderodat/usr/bin/alr]
Alire.Raise_Checked_Error at alire.adb:211
Alire.Environment.Compile at alire-environment.adb:288
Alire.Environment.Compile at alire-environment.adb:330
Alire.Environment.Export at alire-environment.adb:343
Alire.Roots.Export_Build_Environment at alire-roots.adb:88
Alire.Workspace.Deploy_Dependencies at alire-workspace.adb:45
Alr.Commands.Withing.Replace_Current at alr-commands-withing.adb:274
Alr.Commands.Withing.Add at alr-commands-withing.adb:298
Alr.Commands.Withing.Execute at alr-commands-withing.adb:515
Alr.Commands.Execute_By_Name at alr-commands.adb:743
Alr.Commands.Execute at alr-commands.adb:713
Alr.Main at alr-main.adb:28
Main at b__alr-main.adb:1851
[/lib/x86_64-linux-gnu/libc.so.6]
0x7f97c0a441e1
[/home/pmderodat/usr/bin/alr]
0x430538 _start at ???
0xfffffffffffffffe

debug: --->8--- Exception dump end ----->8---
stderr: ALIRE.CHECKED_ERROR
stderr: Trying to set an alredy defined environment variable: LIBRARY_TYPE is already defined as relocatable
stderr: raised ALIRE.CHECKED_ERROR : alire-stored-error:1
[/home/pmderodat/usr/bin/alr]
Alire.Raise_Checked_Error at alire.adb:211
Alire.Environment.Compile at alire-environment.adb:288
Alire.Environment.Compile at alire-environment.adb:330
Alire.Environment.Export at alire-environment.adb:343
Alire.Roots.Export_Build_Environment at alire-roots.adb:88
Alire.Workspace.Deploy_Dependencies at alire-workspace.adb:45
Alr.Commands.Withing.Replace_Current at alr-commands-withing.adb:274
Alr.Commands.Withing.Add at alr-commands-withing.adb:298
Alr.Commands.Withing.Execute at alr-commands-withing.adb:515
Alr.Commands.Execute_By_Name at alr-commands.adb:743
Alr.Commands.Execute at alr-commands.adb:713
Alr.Main at alr-main.adb:28
Main at b__alr-main.adb:1851
[/lib/x86_64-linux-gnu/libc.so.6]
0x7f97c0a441e1
[/home/pmderodat/usr/bin/alr]
0x430538 _start at ???
0xfffffffffffffffe

error: Trying to set an alredy defined environment variable: LIBRARY_TYPE is already defined as relocatable
error: alr encountered an unexpected error, re-run with -d for details.
```

This is with alr 0.7.0-dev, by the way:
```
$ alr version
Alr version: 0.7.0-dev
Alire Library version: 0.7.0-dev
```

**Comment by Fabien-Chouteau** [comment]
> detail: Env: langkit_support (gpr ext) sets 'relocatable' to 'LIBRARY_TYPE'
> detail: Env: libadalang (gpr ext) sets 'relocatable' to 'LIBRARY_TYPE'
> stderr: Trying to set an alredy defined environment variable: LIBRARY_TYPE is already defined as relocatable

`Alr` should accept when the variable is set to the same value...

Do you have `LIBRARY_TYPE` defined in your environment?

**Comment by pmderodat** [comment]
> Do you have `LIBRARY_TYPE` defined in your environment?

You mean as an environemnt variable? In that case no, I don’t.

**Comment by mosteo** [comment]
> `Alr` should accept when the variable is set to the same value...

Besides, Maxim submitted a `spawn` crate for launching subprocesses that seems able to set the environment only for the child process.

**Comment by mosteo** [comment]
alire-project/alire#580 is queued to deal with the `alr with` issue. Should we merge this PR then as-is?

**Comment by pmderodat** [comment]
> [alire-project/alire#580](https://github.com/alire-project/alire/pull/580) is queued to deal with the `alr with` issue. Should we merge this PR then as-is?

Will the upcoming public beta include the fix? If yes, I have no problem updating the PR, but if not, we should probably keep it as-is.

**Comment by mosteo** [comment]
We could update the `0.7` release (yet again :_) ), or have a `0.7.1` down the road... But I'm confused, isn't the PR already updated? Since it passed the checks...

**Comment by pmderodat** [comment]
Absolutely ^^ The checks currently pass because I’ve amended the crates to have `gpr-set-externals` for `LIBRARY_TYPES` only in `langkit_support` (the crash arises when having that in both `langkit_support` and `libadalang`). I have the feeling that the PR is fine as it is currently in any case.

Thanks for your help and for the fix in alire-project/alire#580!

**Review by mosteo — APPROVED** [review]

**Comment by mosteo** [comment]
Alright then, thanks!

**Pull request merged**
