### PR TITLE
AdaCL 5.10.0 nested unit test.

### PR DESCRIPTION
**Pull request by krischik**
As suggested by @mosteo this version of AdaCL contains a test directory with the AUnit tests and a test action. This is quite experimental so it's a draft pull request for now.

### CODE REVIEW

**Comment by krischik** [comment]
Build was successful but `test` action was not executed:

```
Note: Building adacl/adacl.gpr...
Setup
   [mkdir]        object directory for project AdaCL
   [mkdir]        library directory for project AdaCL
Compile
   [Ada]          adacl_config.ads
   [Ada]          adacl-os-low_level.ads
   [Ada]          adacl-strings.adb
   [Ada]          adacl-base.ads
   [Ada]          adacl-limited_base.ads
   [Ada]          adacl.ads
   [Ada]          adacl-trace.adb
   [Ada]          adacl-command_line-getopt.adb
   [Ada]          adacl-command_line.ads
   [Ada]          adacl-os.ads
Build Libraries
   [gprlib]       AdaCL.lexch
   [archive]      libAdaCL.a
   [index]        libAdaCL.a
Build finished successfully in 3.18 seconds.
LISTING EXECUTABLES of crate adacl=5.10.0
Crate adacl does not explicitly declares to build any executable
No default executable has been automatically found either by alr
~/work/alire-index/alire-index
Freeing up 1.7M used by adacl=5.10.0
CRATE adacl=5.10.0 TEST ENDED SUCCESSFULLY
```

**Comment by mosteo** [comment]
Alright, I identified two issues:

1. We aren't using yet `alr test` because in 1.2 it uses dev build, which we don't want.
   1. As a workaround, I just added that we `alr run` any `./test*` folder containing an `alire.toml`
1. Even so, for your post-build to work, it must have explicit `./adacl_test-main`, since `.` is not in the path.

So, at this time, the only thing you should do is correct point 2.

**Comment by krischik** [comment]
I removed the post build block as it would lead the the test run twice.

**Comment by krischik** [comment]
**Closed** — Superseded by pull request #773 AdaCL version 5.10.2

**Comment by krischik** [comment]
**Closed** — Superseded by pull request #773 AdaCL version 5.10.2

**Pull request closed without merging**
