### PR TITLE
sdlada on Windows

### PR DESCRIPTION
**Pull request by Fabien-Chouteau**
With these changes it is now possible to compile and run sdlada project on windows.
`alr -n get --build ada_voxel_space_demo`

Using: https://github.com/alire-project/alire/pull/336, https://github.com/alire-project/alire/pull/452 and https://github.com/alire-project/alire/pull/456.

### CODE REVIEW

**Comment by mosteo** [comment]
I don't know why I had this sitting here for so long, sorry. I've migrated it to the new index so now it's a matter of passing the build tests.

**Comment by mosteo** [comment]
It seems that indeed `sdlada` does not build with CE2020. @Fabien-Chouteau , can you reproduce?

**Comment by Fabien-Chouteau** [comment]
@mosteo yes I can. It is fixed but we need a new release of SDLAda: https://github.com/Lucretia/sdlada/commit/cfb255a751bfaf7e8cbdb5ba4808decb78476ecb

**Comment by mosteo** [comment]
I'm closing this one in favor of #167, please let me know over there about any pending issue with this crate.

**Pull request closed without merging**
