### PR TITLE
Add spawn-24.0.1, spawn_glib-24.0.1 with fixed OS collision

### PR DESCRIPTION
**Pull request by reznikmm**

### CODE REVIEW

**Comment by Fabien-Chouteau** [comment]
```
TESTING CRATE
Note: Testing local crate: spawn_glib=24.0.1
ERROR: Local test of spawn_glib=24.0.1 failed:
ERROR:    Check alire/alr_test_local.log for details.
AVAILABLE LOGS
-rw-r--r-- 1 runner docker 359 Sep 24 08:26 alire/alr_test_local.log
LOG CONTENTS
---8<--- LOG FILE BEGIN: alire/alr_test_local.log
Spawning: alr -d -n build --release
Note: Running post-fetch actions for gtkada=24.0.0...
/usr/bin/bash: line 1: ./configure: Permission denied
stderr: Command ["bash", "-c", "PATH=${DISTRIB_ROOT}/mingw64/bin:${PATH} ./configure"] exited with code 126
ERROR: Command ["bash", "-c", "PATH=${DISTRIB_ROOT}/mingw64/bin:${PATH} ./configure"] exited with code 126
--->8--- LOG FILE END: alire/alr_test_local.log
```

https://github.com/alire-project/alire-index/actions/runs/11009858425/job/30570445949?pr=1232

**Comment by reznikmm** [comment]
Any idea how `configure` script lost executable permissions?

**Comment by reznikmm** [comment]
Alr drops permissions when syncs gtkada to shared dependency folder:

> ls -l /tmp/ac/builds/gtkada_24.0.1_8aa310cb/05561da954afaee17128f59bba699db2f2e4a4215317b2b818a8016192c82334/configure
> -rw-r--r-- 1 runner docker 162964 Sep 24 11:55 /tmp/ac/builds/gtkada_24.0.1_8aa310cb/05561da954afaee17128f59bba699db2f2e4a4215317b2b818a8016192c82334/configure

The CI scripts tries to build `spawn_glib`. To do this alr creates a shared copy of gtkada. It clears executable flag from configure scripts while copying gtkada. Then `post-fetch` action is ran and fails to execute `./configure`.

Please note that alr 2.0.1 works fine, but alr devel (2.1) fails.

**Comment by reznikmm** [comment]
I've opened the issue https://github.com/alire-project/alire/issues/1763

**Review by mosteo — APPROVED** [review]

**Pull request merged**
