### PR TITLE
GTKada 22.0.0

### PR DESCRIPTION
**Pull request by Fabien-Chouteau**

### CODE REVIEW

**Comment by Fabien-Chouteau** [comment]
@mosteo it seems like gtkada's post-fetch action is run before external dependencies (e.g. pkg-config) are installed.
Do you think that's possible?

**Comment by mosteo** [comment]
> @mosteo it seems like gtkada's post-fetch action is run before external dependencies (e.g. pkg-config) are installed. Do you think that's possible?

I don't think that should happen. Cursory code review indicates that `pkg-config` should be deployed and `post-fetch`ed before. And looking at [this log](https://github.com/alire-project/alire-index/runs/4223856417?check_suite_focus=true) it seems to be working in the intended order:

```
393: Note: Deploying release pkg_config=0.29.2...
...
443: Note: Running post_fetch actions for gtkada=22.0.0...
```

May be we are looking at different places?

**Comment by Fabien-Chouteau** [comment]
On my side I have:
```
checking for GTK - version >= 3.24.0... configure: error: pkg-config not found
```
So I will see why I have a different ouput...

**Comment by reznikmm** [comment]
> checking for pkg-config... /c/Strawberry/perl/bin/pkg-config

Looks like a wrong `pkg-config` was found.

**Comment by reznikmm** [comment]
I've printed `PATH` value and I don't see `msys` in it:
```
/usr/bin
/usr/local/bin
/c/Program Files/Git/mingw64/bin
/c/Program Files/Git/usr/bin
/c/Users/runneradmin/bin
/d/a/alire-index/alire-index/alire_install/bin
/d/a/_temp/gnat-2020-20200818-x86_64-windows-bin/bin
/c/Program Files/MongoDB/Server/5.0/bin
/c/aliyun-cli
/c/vcpkg
/c/cf-cli
/c/Program Files (x86)/NSIS
/c/tools/zstd
/c/Program Files/Mercurial
/c/hostedtoolcache/windows/stack/2.7.3/x64
/c/cabal/bin
/c/ghcup/bin
/c/tools/ghc-9.2.1/bin
/c/Program Files/dotnet
/c/mysql/bin
/c/Program Files/R/R-4.1.2/bin/x64
/c/SeleniumWebDrivers/GeckoDriver
/c/Program Files (x86)/sbt/bin
/c/Program Files (x86)/GitHub CLI
/c/Program Files/Git/usr/bin
/c/Program Files (x86)/pipx_bin
/c/hostedtoolcache/windows/go/1.15.15/x64/bin
/c/hostedtoolcache/windows/Python/3.7.9/x64/Scripts
/c/hostedtoolcache/windows/Python/3.7.9/x64
/c/hostedtoolcache/windows/Ruby/2.5.9/x64/bin
/c/tools/kotlinc/bin
/c/hostedtoolcache/windows/Java_Temurin-Hotspot_jdk/8.0.312-7/x64/bin
/c/npm/prefix
/c/Program Files (x86)/Microsoft SDKs/Azure/CLI2/wbin
/c/ProgramData/kind
/c/Program Files/Eclipse Foundation/jdk-8.0.302.8-hotspot/bin
/c/Windows/system32
/c/Windows
/c/Windows/System32/Wbem
/c/Windows/System32/WindowsPowerShell/v1.0
/c/Windows/System32/OpenSSH
/c/ProgramData/Chocolatey/bin
/c/Program Files/Docker
/c/Program Files/PowerShell/7
/c/Program Files/Microsoft/Web Platform Installer
/c/Program Files/dotnet
/c/Program Files/Microsoft SQL Server/130/Tools/Binn
/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn
/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit
/c/Program Files (x86)/Microsoft SQL Server/110/DTS/Binn
/c/Program Files (x86)/Microsoft SQL Server/120/DTS/Binn
/c/Program Files (x86)/Microsoft SQL Server/130/DTS/Binn
/c/Program Files (x86)/Microsoft SQL Server/140/DTS/Binn
/c/Program Files (x86)/Microsoft SQL Server/150/DTS/Binn
/c/Program Files/nodejs
/c/Program Files/OpenSSL/bin
/c/Strawberry/c/bin
/c/Strawberry/perl/site/bin
/c/Strawberry/perl/bin
/c/ProgramData/chocolatey/lib/pulumi/tools/Pulumi/bin
/c/Program Files/TortoiseSVN/bin
/c/Program Files/CMake/bin
/c/ProgramData/chocolatey/lib/maven/apache-maven-3.8.4/bin
/c/Program Files/Microsoft Service Fabric/bin/Fabric/Fabric.Code
/c/Program Files/Microsoft SDKs/Service Fabric/Tools/ServiceFabricLocalClusterManager
/c/Program Files/Git/cmd
/c/Program Files/Git/mingw64/bin
/c/Program Files/Git/usr/bin
/c/tools/php
/c/Program Files (x86)/sbt/bin
/c/SeleniumWebDrivers/ChromeDriver
/c/SeleniumWebDrivers/EdgeDriver
/c/Program Files/Amazon/AWSCLIV2
/c/Program Files/Amazon/SessionManagerPlugin/bin
/c/Program Files/Amazon/AWSSAMCLI/bin
/c/Program Files (x86)/Google/Cloud SDK/google-cloud-sdk/bin
/c/Program Files (x86)/Microsoft BizTalk Server
/c/Program Files/LLVM/bin
/c/Users/runneradmin/.dotnet/tools
/c/Users/runneradmin/.cargo/bin
/c/Users/runneradmin/AppData/Local/Microsoft/WindowsApps
/mingw64/bin
```

**Pull request closed without merging**
