### PR TITLE
Add Raspberry Pi RP2040 and Pico packages

### PR DESCRIPTION
**Pull request by JeremyGrosser**

### CODE REVIEW

**Comment by JeremyGrosser** [comment]
It looks like the CI system doesn't have an arm-eabi toolchain available, so the builds fail.

**Comment by Fabien-Chouteau** [comment]
> It looks like the CI system doesn't have an arm-eabi toolchain available, so the builds fail.

Indeed, I will check it on my setup and let you know.

**Review by Fabien-Chouteau — APPROVED** [review]
Compilation is ok with GNAT Community 2020 arm-elf.

**Review by mosteo — APPROVED** [review]

**Comment by mosteo** [comment]
> Compilation is ok with GNAT Community 2020 arm-elf.

Thanks, I'm going to merge now. Thanks @JeremyGrosser for the submission.

> It looks like the CI system doesn't have an arm-eabi toolchain available, so the builds fail.

Indeed, let's hope to find a solution for this in the not distant future.

**Pull request merged**
