### PR TITLE
dir_iterators 0.0.1

### PR DESCRIPTION
**Pull request by pyjarrett**
An iterator-based recursive directory walker and other iterator-based walker which traces up parent directories.

### CODE REVIEW

**Comment by mosteo** [comment]
Hi @pyjarrett , thanks for your contribution. Given the [error](https://github.com/alire-project/alire-index/pull/284/checks?check_run_id=2781372315#step:7:366), I guess you'll need to narrow down the compilers that are able to build your code. For that you need to add dependencies on more precise versions of the compiler.

If you have the time, you can play with the docker images at https://hub.docker.com/repository/docker/alire/gnat. Alternatively just give the version that you're using as the minimum.

Unfortunately there's not an easy way yet (https://github.com/alire-project/alire/issues/161) to test unindexed crates in all these docker images. You'd need to launch the docker manually, passing the alr binary and your crate folder via `-v` arguments. As I said, time consuming...

**Comment by pyjarrett** [comment]
It's cool, I'll figure it out, I'm use to this sort of thing.  It's been impressive that everything has been so smooth so far to get to this point :)

**Comment by pyjarrett** [comment]
@mosteo Ok, I actually found and fixed two different errors on Ubuntu and Debian (same error both places).  I didn't see a macos image, but hopefully it'll work since it's just using stock Ada 2012 now.

**Comment by mosteo** [comment]
Right, for macOS and Windows we rely on the GH Actions environments. Let's see what happens.

**Comment by mosteo** [comment]
Merged, thanks.

**Pull request merged**
