### PR TITLE
pragmarc 20240810.0.0

### PR DESCRIPTION
**Pull request by bracke**
Created via `alr publish` with `alr 2.0.1`

### CODE REVIEW

**Comment by Fabien-Chouteau** [comment]
@jrcarter are you ok with the publishing of this fork, or would you publish PragmARC yourself?

@bracke Alire is using SemVer for dependency resolution, it would be great to use meaningful versions instead of dates.

**Comment by jrcarter** [comment]
> @jrcarter are you ok with the publishing of this fork, or would you publish PragmARC yourself?

I am happy with Bent Bracke's handling of the PragmARCs for Alire. However, I expect to create a new release resolving Issue #15 before the end of the month.

**Comment by bracke** [comment]
@Fabien-Chouteau I was told Alire supported date based version numbering?
The original project does not have version numbers/releases.

**Comment by Fabien-Chouteau** [comment]
Date based version are compatible but it's bad practice with regards to dependency resolution.

**Comment by bracke** [comment]
But the project has no version number, so giving the fork a version number would not reflect anything. 
I have no idea whether a new version contains breaking changes. I'm just passing them along.

**Comment by mosteo** [comment]
We talked about this and all crates from @jrcarter maintained by @bracke follow this convention. In retrospect these should have been pre-1 versions (`0.20240810`) or rather have the date in the build (`0.1+20240810`), to allow seamlessly transitioning to semver in the future. 

It would be messy to change them now they're published, although maybe it's better now rather than latter.

**Review by mosteo — APPROVED** [review]

**Pull request merged**
