### PR TITLE
HiRTOS 1.0.0

### PR DESCRIPTION
**Pull request by jgrivera67**
HiRTOS crates published as a submission to the Ada/SPARK crate of the year 2023 contest, in the embedded software category. HiRTOS is a high-integrity RTOS kernel and a separation kernel written in SPARK Ada

### CODE REVIEW

**Comment by jgrivera67** [comment]
My PR is faililing the required builds due to the following GNAT bug:
```
+===========================GNAT BUG DETECTED==============================+
| 12.2.0 (arm-eabi) in gimplify_modify_expr, at gimplify.cc:6255           |
| Error detected around /home/runner/work/alire-index/alire-index/hirtos_1.0.0_3a6dd675/src/porting_layer/cpu_architectures/armv8r_aarch32/hirtos_cpu_arch_interface-interrupt_controller.ads:399:9|
| Compiling /home/runner/work/alire-index/alire-index/hirtos_1.0.0_3a6dd675/src/porting_layer/cpu_architectures/armv8r_aarch32/hirtos_cpu_arch_interface-interrupt_controller.adb|
| Please submit a bug report; see https://gcc.gnu.org/bugs/ .              |
| Use a subject line meaningful to you and us to track the bug.            |
| Include the entire contents of this bug box in the report.               |
| Include the exact command that you entered.                              |
| Also include sources listed below.                                       |
+==========================================================================+
```

**Comment by Fabien-Chouteau** [comment]
What compiler and version are you using for your development?

**Comment by jgrivera67** [comment]
> What compiler and version are you using for your development?

Hi Fabien, I was using using 12.2.1, since I declared the following dependency in the manifest file:
```
[[depends-on]]
gnat_arm_elf = "^12.2.1"
```
The build log indicates that gnat_arm_elf 12.2.0 is being used. I don't hit this compiler bug on 12.2.1. 

Anyway, to be safe, I upgraded to use gnat_arm_elf 13.2.1 and all builds are passing now.
However, I still needed to keep the source of `portable_minimal_ada_rts` in the same source tree
as HiRTOS, instead of being a separate crate, as the PR to update the `portable_minimal_ada_rts`
crate in `alire-index` is currently failing three native builds, due to old compilers being used.

I created ticket https://github.com/jgrivera67/HiRTOS/issues/13 in the HiRTOS repo, so that once I
can republish the `portable_minimal_ada_rts` crate, I will remove its source code from the HiRTOS 
source tree and add a dependency on that crate in the HiRTOS Alire manifest.

**Comment by jgrivera67** [comment]
Hi @Fabien-Chouteau and @mosteo can you please tell me if there is anything else I need to change to get approval to merge this PR?

**Comment by jgrivera67** [comment]
Hi @Fabien-Chouteau , I was checking if there is anything else I can do for this PR to get approved and merged before the end of the year, so that my HiRTOS crates can compete for the crate of the year - embedded category?  

Thanks, 

German

**Review by Fabien-Chouteau — APPROVED** [review]

**Pull request merged**
