### PR TITLE
inotify 1.0.1

### PR DESCRIPTION
**Pull request by onox**

### CODE REVIEW

**Comment by onox** [comment]
@mosteo `Check PR` doesn't understand `alr search --crates`

**Comment by mosteo** [comment]
> @mosteo `Check PR` doesn't understand `alr search --crates`

I'm on it

**Comment by mosteo** [comment]
The problem with the "Check PR" workflow should be fixed now... But there is some other problem with the macOS build.

**Comment by onox** [comment]
> But there is some other problem with the macOS build

The macOS and windows builds should not run, inotify is for Linux only.

**Comment by mosteo** [comment]
Right you are. For some reason the linux alr version was compiled instead. I'll check what's going on.

**Review by mosteo — APPROVED** [review]

**Comment by mosteo** [comment]
Should be fixed for the future, sorry for the inconveniences.

**Comment by onox** [comment]
Thank you :+1:

**Pull request merged**
