### PR TITLE
Create lea-0.87.0.toml

### PR DESCRIPTION
**Pull request by zertovitch**
Added the LEA application

### CODE REVIEW

**Review by mosteo — APPROVED** [review]

**Comment by mosteo** [comment]
It seems it is not building on Windows because of the compiler dependency. Should I still merge it like this?

**Comment by zertovitch** [comment]
On a local machine, the crate proposal builds seamlessly. I had to set a maximum to the gnat version because of a subtle incompatibility in gcc on an intrinsic function (see https://github.com/zertovitch/gwindows/issues/9 ). But recent gcc versions seem to have removed this glitch (notably, GNAT Pro 23.0).
I will refine the criterium and perhaps move it to the gwindows crate later, after probably a couple of iterations and when I have a clearer picture which versions are impacted.

**Comment by zertovitch** [comment]
Short answer: go for it!

**Comment by zertovitch** [comment]
Probably the issue with the compiler version will disappear from itself in an upcoming GNAT version in Alire since LEA builds already OK with GNAT Pro 23.

**Comment by mosteo** [comment]
Alright, merging then!

**Pull request merged**
