### PR TITLE
Add tash 8.7.0 (first Alire release).

### PR DESCRIPTION
**Pull request by simonjwright**
Previously known as tcladashell.

### CODE REVIEW

**Comment by Fabien-Chouteau** [comment]
Hi @simonjwright 
```
ERROR: A post-fetch action failed, re-run with -vv -d for details
, stderr debconf: delaying package configuration, since apt-utils is not installed
debconf: delaying package configuration, since apt-utils is not installed
/bin/sh: 1: tclsh: not found
make: *** [makefile:29: tcl_record_sizes.c] Error 127
stderr: Command ["make", "-C", "src", "tcl_record_sizes.ads"] exited with code 2
```

Does this need another external dependency?

**Comment by simonjwright** [comment]
I’m _pretty_ sure that the issue is that Debian, at any rate in _bullseye_, doesn’t have `tclsh` but only `tclsh8.6` (`tclsh` is usually a symlink to this). `ubuntu-latest` doesn’t have a problem.

I’ll try that, though long-term there will be an issue when Tcl/Tk gets updated beyond 8.6 -- ideally sorted using `pkg-config`, but Homebrew has a problem with that -- is there an Alire way of setting an environment variable to the result of running a script?

**Comment by simonjwright** [comment]
I was right about the tclsh[8.6] issue!

The Toolchain/windows-latest issue looks to be unrelated to this PR? the Build Crate/windows-latest was successful.

**Comment by simonjwright** [comment]
@Fabien-Chouteau I want to request a review, but don’t see how to? The _Reviewers_ section at top right isn’t live

**Comment by mosteo** [comment]
> @Fabien-Chouteau I want to request a review, but don’t see how to? The _Reviewers_ section at top right isn’t live

That's bizarre. Not sure what can be going on.

I've relaunched the Windows test in case it was transitory glitch.

**Review by mosteo — APPROVED** [review]

**Comment by mosteo** [comment]
> ideally sorted using `pkg-config`, but Homebrew has a problem with that -- is there an Alire way of setting an environment variable to the result of running a script?

Not currently, but I'm also aware of this issue. We may need to add this capability to our external definitions.

> I've relaunched the Windows test in case it was transitory glitch.

And it was, so merging now.

**Comment by simonjwright** [comment]
That seems to have worked! Good.

Don’t understand the difference between a 'toolchain' and a 'build crate' run, the log I just looked at went ahead and built the crate?

Could I have requested the re-run?

Anyway, :relaxes:

**Comment by mosteo** [comment]
> Don’t understand the difference between a 'toolchain' and a 'build crate' run

This is just the naming of the workflows, that could be improved, but the essence is that a 'toolchain' build will use the compilers indexed by Alire, whereas the 'build crate' will use the native compilers of each distro/platform if defined, or the latest GNAT CE otherwise.

> Could I have requested the re-run?

I'm not sure about that. If the option is available to you, you'll see at the top of the log of the run: 

image

**Comment by Fabien-Chouteau** [comment]
> > I've relaunched the Windows test in case it was transitory glitch.
> 
> And it was, so merging now.

Looks like our integrity check detected a bad download
```
ERROR: release integrity test failed: expected [sha256:3126cd6fe82b9428ba1bd50f7d7a5e108668a41da445184a6bbe13d2543fd2d0] but got [sha256:163df270842365bdceebcedcc53dad9b950d11e3463b4e461060866353acdd3d]
```

**Pull request merged**
