### PR TITLE
Add blake2s 0.1.0

### PR DESCRIPTION
**Pull request by lkujaw**
Hi,

This is only the library component, as I want to keep the existing Makefile setup unified if possible. I'm not too familiar with gprbuild, so if there's an easy way to run the test program as part of the build, please let me know.

Thanks, Lev

### CODE REVIEW

**Comment by mosteo** [comment]
Thanks for your contribution, @lkujaw . It seems that the default checkout on Windows is preserving line terminators, which you are checking in your style settings:

```
octets.ads:1:79: (style) incorrect line terminator
```

If this check is not critical to you, you could disable it with `-gnaty-d`. Otherwise, I guess the repository should include [configuration on how to treat line terminators](https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings#per-repository-settings).

**Comment by mosteo** [comment]
> This is only the library component, as I want to keep the existing Makefile setup unified if possible. I'm not too familiar with gprbuild, so if there's an easy way to run the test program as part of the build, please let me know.

Actually we prefer that test programs are not run by default. We may add features to perform self-tests in a separate way in the future.

**Comment by lkujaw** [comment]
Thanks for the feedback. I decided to remove the CRLF check altogether; hopefully that will make working with the source code easier on those platforms.

**Review by mosteo — APPROVED** [review]

**Comment by mosteo** [comment]
Merged, thanks.

**Comment by Fabien-Chouteau** [comment]
@lkujaw I see that you are using the gpr file generated by Alire. The default in the gpr file is to enable all checks and compile in debug mode. You can change that to avoid compilation issue like the CRLF thing for the user of your crate, and also compile in "optimize" mode for better performance.

Maybe we should change the defaults for the gpr generated by `alr`. I did it this way for a better programming experience (debug enabled, all checks to catch your errors), but then it's bad when the crate is published in the index...

**Pull request merged**
