### PR TITLE
Add ada_toml 0.3.0

### PR DESCRIPTION
**Pull request by pmderodat**

### CODE REVIEW

**Comment by mosteo** [comment]
The error is puzzling. I don't think at this time that the problem is in you packaging, will investigate.

**Comment by pmderodat** [comment]
Ok thanks! Even more puzzling to me ;-)

**Comment by mosteo** [comment]
The problem is that I cannot replicate it locally even on the very same OS version...

**Comment by mosteo** [comment]
OK, found the issue, for which I will submit a patch to our CI scripts shortly. I've tested your submission in my fork so it's safe to merge.

**Review by mosteo — APPROVED** [review]

**Comment by pmderodat** [comment]
Awesome, thank you very much for the quick fix! :-)

**Pull request merged**
