### PR TITLE
OpenGLAda 0.9.0

### PR DESCRIPTION
**Pull request by flyx**
Split into four crates due to optional dependencies.

### CODE REVIEW

**Comment by mosteo** [comment]
Thanks a lot, @flyx, this is great.

I'd only suggest to add some tags to the crates. You don't need to repackage, just update the manifests in this PR. This way your crates can be better located at https://alire.ada.dev/

**Comment by flyx** [comment]
The macOS build possibly fails because of the required non-Ada dependencies. Strange that there is no log available.

**Review by mosteo — APPROVED** [review]

**Comment by mosteo** [comment]
GH actions are not 100%-proof. They seem to be acting up right now, I'll relaunch them in a while.

**Comment by mosteo** [comment]
Indeed https://www.githubstatus.com/ reports degraded actions.

**Comment by mosteo** [comment]
In the end it was GH's own trouble and now all tests have passed. Merging, thanks!

**Pull request merged**
