### PR TITLE
ada_voxel_space_demo: add release v1.0.1

### PR DESCRIPTION
**Pull request by Fabien-Chouteau**

### CODE REVIEW

**Comment by Fabien-Chouteau** [comment]
The build check failed because `sudo apt-get install --no-remove -q -q -y libsdl2-dev` failed.

@mosteo can you restart the checks?

**Comment by mosteo** [comment]
It failed again, but this time is something wrong with the check script. I'll take a deeper look.

**Comment by mosteo** [comment]
The failure with libsdl2-dev was due to the debian-stable docker image being too old. I'm refreshing it now but I guess we will need something more robust/automated moving forward.

**Comment by mosteo** [comment]
Should pass checks after #103 is in, once sdlada is enabled in Windows and MacOS.

**Comment by mosteo** [comment]
I'm going to try to enable sdlada on MacOS.

**Comment by mosteo** [comment]
Everything checks out, thanks for the patience.

**Comment by Fabien-Chouteau** [comment]
No problem, thank you Alejandro.

**Pull request merged**
