### PR TITLE
wikibook 1.0.0

### PR DESCRIPTION
**Pull request by krischik**
Created via `alr publish` with `alr 2.0`

### CODE REVIEW

**Comment by krischik** [comment]
ubuntu-lts is a little bit outdated:

```
gnat1: invalid switch: -gnat2022
gnat1: invalid switch: -gnat2022
gnat1: invalid switch: -gnat2022
gnat1: invalid switch: -gnat2022
```

**Comment by mosteo** [comment]
> ubuntu-lts is a little bit outdated:

In that case you need a minimum version dependency on `gnat`.

**Comment by krischik** [comment]
> In that case you need a minimum version dependency on `gnat`.

Since we have sub-crates that means a new tar file :-( .

**Comment by krischik** [comment]
@mosteo done.

**Review by mosteo — APPROVED** [review]

**Comment by mosteo** [comment]
Merged, thanks.

**Pull request merged**
