### PR TITLE
Euler Tools 1.0.1

### PR DESCRIPTION
**Pull request by rocher**
First public release.

### CODE REVIEW

**Comment by mosteo** [comment]
Your dependency on gnat is only half-complete because it also admits the CE editions with versions 2019 and up. You can fix it as `gnat>=12 & gnat<2000` for example.

**Comment by rocher** [comment]
> Your dependency on gnat is only half-complete because it also admits the CE editions with versions 2019 and up. You can fix it as `gnat>=12 & gnat<2000` for example.

Yes, I saw this problem.
Also, I was using the `-gnat2022` switch, which looks like is only supported in `ubuntu-latest`. Changed to `-gnat2020` and run unit tests in all platform and now it works.

**Comment by rocher** [comment]
Don't understand why [this workflow run passed](https://github.com/rocher/euler_tools/actions/runs/4223138022) and not the one in the current PR.
What I want is to use the currently implemented Ada 2022 extensions: the `-gnat2020` switch worked fine for me. Why not here?

**Comment by mosteo** [comment]
That's because the failing workflow is using a GNAT Community 2020 compiler, which doesn't support the switch. That's why you can avoid the problem with the extra restriction on versions in the gnat dependency.

**Comment by rocher** [comment]
Ok, fixed dependencies but failed again: [was this a system error](https://github.com/alire-project/alire-index/actions/runs/4225834266/jobs/7338591104#step:6:47)?
Will push again, just in case.

**Review by mosteo — APPROVED** [review]

**Comment by mosteo** [comment]
> Ok, fixed dependencies but failed again: [was this a system error](https://github.com/alire-project/alire-index/actions/runs/4225834266/jobs/7338591104#step:6:47)?

Yes, I've seen that before on macOS instances; it's some kind of disk failure. Re-running as you did is enough to fix it.

**Pull request merged**
