### PR TITLE
Create task_coroutines-0.1.0.toml

### PR DESCRIPTION
**Pull request by Fabien-Chouteau**

### CODE REVIEW

**Review by mosteo — COMMENTED** [review]
Neat, I wanted to take a stab at this in the past but I see I'm doubly late...

**Comment by mosteo** [comment]
Mmm, don't know why checks aren't getting triggered...

**Comment by Fabien-Chouteau** [comment]
I tried to re-open the PR... Looks like something's wrong on GitHub side.

**Comment by mosteo** [comment]
We have a problem with the diagnostic message, but the root cause is that the new manifest should be filed under an extra folder `task_coroutines` ^_^'

**Pull request closed without merging**
