### PR TITLE
Added get_password index file

### PR DESCRIPTION
**Pull request by riccardo-bernardini**

### CODE REVIEW

**Comment by jquorning** [comment]
@fintatarta I guess the file should be named `index/ge/get_password/get_password-1.0.0-rc.toml`.

**Comment by Fabien-Chouteau** [comment]
Indeed @jquorning :+1:

**Review by Fabien-Chouteau — CHANGES_REQUESTED** [review]
file path should be `index/ge/get_password/get_password-1.0.0-rc.toml`.

**Comment by mosteo** [comment]
This PR should be reopened against the `stable-1.2` branch, which is the current stable. In my experience it is not enough to rebase and change the base branch, due to some limitation in the Github actions framework, so I'm closing it now. Sorry for the inconvenience.

**Pull request closed without merging**
