### PR TITLE
Install indexed gprbuild when necessary

### LINKED ISSUE #900: Install `gprbuild` too when a cross-compiler is automatically selected
Otherwise the native `gprbuild` is unable to locate/use the compiler.

See e.g. https://github.com/alire-project/alire-index/pull/417

### PR DESCRIPTION
**Pull request by mosteo**
Fixes https://github.com/alire-project/alire/issues/900

Tested in https://github.com/mosteo/alire-index/pull/44 and https://github.com/mosteo/alire-index/pull/45

### CODE REVIEW

**Review by Fabien-Chouteau — APPROVED** [review]

**Comment by Fabien-Chouteau** [comment]
I feel like this is showing a problem that we have with gprbuild.

Maybe we should pick a version of gprbuild, package it with Alire and that what will be used all the time.

**Comment by mosteo** [comment]
The problem with that is that a gprbuild installed by Alire doesn't detect a system GNAT. Maybe we should automate from alr itself what this PR is doing.

**Comment by Fabien-Chouteau** [comment]
> gprbuild installed by Alire doesn't detect a system GNAT

That might only be true for Debian/Ubuntu, but I am not sure. With a little bit of research we may be able to make it work for both cases/

**Comment by mosteo** [comment]
That would simplify things, yep.

**Pull request merged**
