### PR TITLE
simcpucli 0.1.0

### PR DESCRIPTION
**Pull request by BrentSeidel**
Created via `alr publish` with `alr 2.0.1`

### CODE REVIEW

**Comment by BrentSeidel** [comment]
Do you know what gnat version openSuSe uses so that I can request a later version?  Otherwise I can just omit it like I did with my lispcli crate.

**Comment by BrentSeidel** [comment]
Did something change with the MacOS build environment?  It looks like it is failing before it actually tries to fetch and build my crate.  I also develop on MacOS and it builds fine there.

**Comment by mosteo** [comment]
> Do you know what gnat version openSuSe uses so that I can request a later version? Otherwise I can just omit it like I did with my lispcli crate.

Open SUSE is on GNAT 7.5

**Comment by BrentSeidel** [comment]
With the gnat > 7.5 dependency, OpenSuSe tries to install gnat 14.1.3, but the installation fails.  Should I disable this for SuSe or just let it go?

**Comment by mosteo** [comment]
This is for us to fix in the opensuse support. No need to change anything.

**Review by mosteo — APPROVED** [review]

**Pull request merged**
