### PR TITLE
Feat/devel 0.5 spdx

### PR DESCRIPTION
**Pull request by Fabien-Chouteau**

### CODE REVIEW

**Review by mosteo — APPROVED** [review]

**Comment by mosteo** [comment]
`startup_gen` (actually `libgpr`?) is failing on macOS:

```
/Users/runner/work/alire-index/alire-index/startup_gen_21.0.0_75bdb097/alire/cache/dependencies/libgpr_21.0.0_49263e36/gpr/src/gpr_imports.c: In function '__gpr_file_time':
/Users/runner/work/alire-index/alire-index/startup_gen_21.0.0_75bdb097/alire/cache/dependencies/libgpr_21.0.0_49263e36/gpr/src/gpr_imports.c:171:38: error: 'struct stat' has no member named 'st_mtim'; did you mean 'st_mode'?
     if (__builtin_ssubll_overflow(sb.st_mtim.tv_sec, ada_epoch_offset, &result)) {
                                      ^~~~~~~
                                      st_mode
/Users/runner/work/alire-index/alire-index/startup_gen_21.0.0_75bdb097/alire/cache/dependencies/libgpr_21.0.0_49263e36/gpr/src/gpr_imports.c:179:46: error: 'struct stat' has no member named 'st_mtim'; did you mean 'st_mode'?
     if (__builtin_saddll_overflow(result, sb.st_mtim.tv_nsec, &result)) {
                                              ^~~~~~~
                                              st_mode
gprbuild: *** compilation phase failed
```

**Comment by Fabien-Chouteau** [comment]
Looks like the `post-fetch` is not executed: https://github.com/alire-project/alire-index/blob/stable-0.4/index/li/libgpr/libgpr-21.0.0.toml

**Comment by mosteo** [comment]
OK, then this one might be the cause: https://github.com/alire-project/alire/issues/633

**Comment by mosteo** [comment]
I will merge for the time being as this is for the `devel` branch, and the fix is unrelated to the index definition.

**Pull request merged**
