### PR TITLE
Devel 1.1

### PR DESCRIPTION
**Pull request by hgrodriguez**

### CODE REVIEW

**Comment by mosteo** [comment]
Hello Holger, thanks for your submission. I'm ironing out some issues with our checks and will run them once things are fixed, thanks for your patience.

**Comment by Fabien-Chouteau** [comment]
Hello @hgrodriguez,

I think the name of your crate will be confusing for user since ZFP is usually the name of a run-time but your crate is not a run-time.

**Comment by hgrodriguez** [comment]
@Fabien-Chouteau Thanks for the feedback. Any chance to reject this pull request and get rid of it, as I do not want to confuse people or create any problems. Thanks. [I will learn more before I do anything else.]

**Comment by Fabien-Chouteau** [comment]
No problem @hgrodriguez, I just think you need a slightly better name.

Maybe `rp2040_generic_bsp`?

**Comment by hgrodriguez** [comment]
Hi Fabien, thanks for your support, please reject this pull request and I will go back to my bench and think about it. It is obviously not fit for purpose as I was hoping for. Thanks again and sorry for wasting your time.

**Comment by Fabien-Chouteau** [comment]
> It is obviously not fit for purpose as I was hoping for. 

I didn't say this crate is not fine on its own.

> Thanks again and sorry for wasting your time.

No problem, we are here to help ;)

**Pull request closed without merging**
