### PR TITLE
bbt 0.0.5

### PR DESCRIPTION
**Pull request by LionelDraghi**
Created via `alr publish` with `alr 2.0.1`

### CODE REVIEW

**Comment by Fabien-Chouteau** [comment]
Hello @LionelDraghi, there are some link errors on windows:
```
C:/Users/runneradmin/AppData/Local/alire/cache/toolchains/gnat_native_14.1.3_6c25884a/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: bbt-main.o:bbt-main.adb:(.text+0x3): undefined reference to `__fentry__'
C:/Users/runneradmin/AppData/Local/alire/cache/toolchains/gnat_native_14.1.3_6c25884a/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: bbt-main.o: in function `bbt__main__put_help':
```

The solution might be here: https://stackoverflow.com/questions/55566393/how-to-pass-pg-to-gcc-in-cygwin

**Comment by mosteo** [comment]
With our latest release, which runs on aarch64 on the latest macOS, there are also these errors:
```
Undefined symbols for architecture arm64:
  "__mcount", referenced from:
      _bbt__main__put_help__B32b___finalizer.5 in bbt-main.o
      _bbt__main__put_help.4 in bbt-main.o
      __ada_bbt__main in bbt-main.o
      _bbt__main__put_settings__checkbox.27 in bbt-main.o
      _bbt__main__put_settings.10 in bbt-main.o
      _bbt__main__put_settings__B95b___finalizer.11 in bbt-main.o
      _bbt__main__put_settings__B134b___finalizer.12 in bbt-main.o
```

**Comment by mosteo** [comment]
With our latest release, which runs on aarch64 on the latest macOS, there are also these errors:
```
Undefined symbols for architecture arm64:
  "__mcount", referenced from:
      _bbt__main__put_help__B32b___finalizer.5 in bbt-main.o
      _bbt__main__put_help.4 in bbt-main.o
      __ada_bbt__main in bbt-main.o
      _bbt__main__put_settings__checkbox.27 in bbt-main.o
      _bbt__main__put_settings.10 in bbt-main.o
      _bbt__main__put_settings__B95b___finalizer.11 in bbt-main.o
      _bbt__main__put_settings__B134b___finalizer.12 in bbt-main.o
```

**Comment by LionelDraghi** [comment]
Hi Alex and Fabien, 
both error are due to the same misuse of gprof instrumentation.
I removed it, hope this is the solution.

**Pull request closed without merging**
