### PR TITLE
cortex_m 1.0.0

### PR DESCRIPTION
**Pull request by Fabien-Chouteau**

### CODE REVIEW

**Comment by Fabien-Chouteau** [comment]
@mosteo This crate has a config variable without default. That's why the builds fail.

**Review by mosteo — APPROVED** [review]

**Comment by mosteo** [comment]
> @mosteo This crate has a config variable without default. That's why the builds fail.

For these cases the advice is to have a nested crate that supplies the missing info and is configured as a test action. In case you want to add this in the future.

**Comment by Fabien-Chouteau** [comment]
I do have a nested crate. How do I specify it should be used for testing?

**Comment by mosteo** [comment]
Then you add this to your main crate:
```
[[actions]]
type = "test"
directory = "your/nested/crate/path"
command = ["alr", "build"]
```
The `alr build` could be an `alr run` if you want to run unit tests or something.

**Pull request merged**
