### PR TITLE
a0b_armv7m 0.2.0

### PR DESCRIPTION
**Pull request by godunko**
Created via `alr publish` with `alr 2.0.2+9b80158`

Depends-On: https://github.com/alire-project/alire-index/pull/1307

### CODE REVIEW

**Comment by mosteo** [comment]
> Depends-On: #1307

FYI, you can submit several crates together to be able to test them all simultaneously, although this is not doable through `alr`. You'll have to manually submit al new manifests in a single PR.

**Comment by mosteo** [comment]
Just a heads-up, there are failures after relaunching the checks.

**Review by mosteo — APPROVED** [review]

**Comment by godunko** [comment]
> Just a heads-up, there are failures after relaunching the checks.

It is expected, PR needs to be rebased to pass CI

**Comment by mosteo** [comment]
> It is expected, PR needs to be rebased to pass CI

Ah, of course...

**Pull request merged**
