### PR TITLE
Add trendy_test 0.0.1

### PR DESCRIPTION
**Pull request by pyjarrett**

### CODE REVIEW

**Comment by Fabien-Chouteau** [comment]
Hi @pyjarrett,

This is a great library :+1: 

```ada
package Ada.Numerics.Ada.Numerics.Discrete_Random is
...
   function Random
     (Gen   : Generator;
      First : Result_Subtype;
      Last  : Result_Subtype) return Result_Subtype;
...
```
Is an Ada202X feature: http://www.ada-auth.org/cgi-bin/cvsweb.cgi/ai12s/ai12-0144-1.txt?rev=1.13
Which means it is not available in GNAT 10.3 (but will be in GNAT 11.2).
I would suggest to stay on Ada 2012 for maximum compiler compatibility.
Here is how I would write it in Ada2012:
```diff
diff --git a/src/trendy_test.adb b/src/trendy_test.adb
index da726a7..fa8bfe0 100644
--- a/src/trendy_test.adb
+++ b/src/trendy_test.adb
@@ -188,7 +188,9 @@ package body Trendy_Test is

     -- Produces a pseudo-random order of tests.
     function Shuffle (V : Test_Procedure_Vectors.Vector) return Test_Procedure_Vectors.Vector is
-        package Positive_Random is new Ada.Numerics.Discrete_Random(Result_Subtype => Positive);
+
+        subtype Random_Range is Natural range 1 .. Natural(V.Length);
+        package Positive_Random is new Ada.Numerics.Discrete_Random(Random_Range);
         Generator          : Positive_Random.Generator;
         Shuffle_Runs       : constant Natural := 5;
         Shuffle_Iterations : constant Natural := Natural(V.Length) * Shuffle_Runs;
@@ -202,8 +204,8 @@ package body Trendy_Test is

         return Result : Test_Procedure_Vectors.Vector := V.Copy do
             for Iteration in 1 .. Shuffle_Iterations loop
-                I := Positive_Random.Random(Generator, 1, Positive(V.Length));
-                J := Positive_Random.Random(Generator, 1, Positive(V.Length));
+                I := Positive_Random.Random(Generator);
+                J := Positive_Random.Random(Generator);
                 Result.Swap(I, J);
             end loop;
         end return;


```

Other comments:
 - You should change the default build flags in [trendy_test.gpr](https://github.com/pyjarrett/trendy_test/blob/main/trendy_test.gpr) to have better performance and compatibility for your users (disable all and use optimize build mode).
 - `alire.lock` should not be checked-in your repo, and not in the releases crate

**Comment by pyjarrett** [comment]
> alire.lock should not be checked-in your repo, and not in the releases crate

Oh, I guess this is for libraries only, like with [this recommendation for cargo](https://stackoverflow.com/questions/62861623/should-cargo-lock-be-committed-when-the-crate-is-both-a-rust-library-and-an-exec).

From https://alire.ada.dev/docs/#first-steps :

> A companion lock file, alire.lock, stores information about the dependency solution and overrides. These two files can be safely put under version control.

**Comment by Fabien-Chouteau** [comment]
> From https://alire.ada.dev/docs/#first-steps :
> 
> > A companion lock file, alire.lock, stores information about the dependency solution and overrides. These two files can be safely put under version control.

@mosteo we might want to update this?

**Comment by mosteo** [comment]
> @mosteo we might want to update this?

Yup, will do.

**Review by mosteo — DISMISSED** [review]

**Comment by pyjarrett** [comment]
I screwed up some changes and have more stuff to fix, don't merge this.

**Comment by pyjarrett** [comment]
Thanks very much to @Fabien-Chouteau's suggestions, this should work better now (I hope, but I've already been wrong once).

**Review by mosteo — APPROVED** [review]

**Comment by mosteo** [comment]
Sorry, I'm on vacation and a bit disconnected. Is this one ready for merge then?

**Comment by pyjarrett** [comment]
It's ready now.

**Comment by Fabien-Chouteau** [comment]
Great contribution @pyjarrett !

**Pull request merged**
