### PR TITLE
Adare Kem and Sign PQC Packages. includes all necessary files to build and use.

### PR DESCRIPTION
**Pull request by danieagle**
Hi!

These commits includes two packages: one to sign and one kem :-)
all necessary files to build and use are already included built-in.
all files or are MIT or are a type of public domain

God and Mary and Cia Blesses all yours,
GrateFull,
Dani.

### CODE REVIEW

**Comment by mosteo** [comment]
There seems to be an [issue](https://github.com/alire-project/alire-index/actions/runs/10408845685/job/28828303300?pr=1199#step:7:764) with compilation on Windows. You can push updates to this PR, checks should now run automatically after being approved for the first time.

**Comment by danieagle** [comment]
> There seems to be an [issue](https://github.com/alire-project/alire-index/actions/runs/10408845685/job/28828303300?pr=1199#step:7:764) with compilation on Windows. You can push updates to this PR, checks should now run automatically after being approved for the first time.

Done! and Very Very Very Thanks for the patience with me :-)

God and Mary and Cia Blesses all yours,
GrateFull,
Dani.

**Comment by danieagle** [comment]
Hi! @mosteo :-)

I Update package and the .toml file.

> You can push updates to this PR, checks should now run automatically after being approved for the first time.

It is waiting approval :-)

Thanks! for your hard work and care with me!

God and Mary blesses yours all,
Dani.

**Comment by mosteo** [comment]
Ah, I guess I will have to approve until your first PR is merged. Don't hesitate to ping me as needed.

**Comment by danieagle** [comment]
> Ah, I guess I will have to approve until your first PR is merged. Don't hesitate to ping me as needed.

Hi! @mosteo :-)

All checks ok

You or someone can conclude the inclusion? :-)

Very Very Very Thanks!
God and Mary Blesses all yours,
GrateFull,
Dani. :-)

**Review by Fabien-Chouteau — APPROVED** [review]

**Pull request merged**
