### PR TITLE
a0b_i2c 0.1.0

### PR DESCRIPTION
**Pull request by godunko**
Created via `alr publish` with `alr 2.0.2+9b80158`

### CODE REVIEW

**Comment by godunko** [comment]
Selftest requires `arm-eabi` target  and `light-cortex-m0` runtime, it seems they are not provided by Ubuntu/Debian distro toolchains, and Alire's GNAT is not used for some reason.

Is there some combination of target/runtime that is present on all platforms?

Or is there some configuration parameters to skip builds with distro toolchain in CI?

**Comment by mosteo** [comment]
On cursory look, the failure seems to be that the cross-compiler is installed but the compatible gprbuild, so the distro-provided one is unable to find the compiler. That's for me to fix.

**Comment by godunko** [comment]
Thanks! 

I've submitted one more MR (https://github.com/alire-project/alire-index/pull/1255) and CI works fine on it. The difference is that `a0b_stm32f401` crate has `gnat_arm_elf` in dependencies, while `a0b_i2c` crate doesn't have such dependency and it added by the `selftest` subcrate.

**Comment by mosteo** [comment]
> The difference is that `a0b_stm32f401` crate has `gnat_arm_elf` in dependencies, while `a0b_i2c` crate doesn't have such dependency and it added by the `selftest` subcrate.

Right. The CI check isn't clever enough to know where tests are and doesn't proactively install `gprbuild`. A workaround for the time being would be to add a dependency on `gprbuild` in the testing crate itself, besides on gnat. Still, I want to have a proper solution to this (but you may try it if you want).

**Comment by godunko** [comment]
Adding of

```
gprbuild = "*"
```

has undesirable side effect on my setup, it attempts to install `gprbuild` provided by the system (Ubuntu 22.04), and not provided by Alire :( Adding of

```
gprbuild = "^22.0.1"
```

works on my side, but it seems CI fails on MacOS.

**Comment by mosteo** [comment]
I see. This is because only the latest toolchains work on the latest macOS ARM runners.

Let me see if I can come up with a general fix. If you want the crates merged already, given that we know the issue is unrelated, I can merge them so you don't have to wait.

**Comment by godunko** [comment]
Up to you, I can wait for few days, I have more crates to add selftests and to prepare MRs.

**Comment by mosteo** [comment]
This issue should be fixed for the future, I hope. Thanks for the patience.

**Review by mosteo — APPROVED** [review]

**Pull request merged**
