### PR TITLE
sqlite_ada 1.0.1

### PR DESCRIPTION
**Pull request by nytpu**
Add thick(-ish) bindings to SQLite: https://git.sr.ht/~nytpu/sqlite-ada

One note: I could change `SQLITE_USE_EXTERNAL` to default to `true` instead of `false` and add [libsqlite3](https://github.com/alire-project/alire-index/blob/stable-1.2.1/index/li/libsqlite3/libsqlite3-external.toml) as a dependency if you all would prefer, but the primary motivation behind writing these bindings from scratch was to allow customizing [SQLite compile options](https://sqlite.org/compile.html) and statically link extensions, which makes the statically linked SQLite amalgamation more appealing than using the system's dynamic library (also makes the library completely free of external dependencies from an Alire perspective)

### CODE REVIEW

**Comment by Fabien-Chouteau** [comment]
Thanks @nytpu 

> One note: I could change `SQLITE_USE_EXTERNAL` to default to `true` instead of `false` and add [libsqlite3](https://github.com/alire-project/alire-index/blob/stable-1.2.1/index/li/libsqlite3/libsqlite3-external.toml) as a dependency if you all would prefer,

I don't really have an opinion on this, external may also bring security updates instead of a fixed version of libsqlite, on the other hand I like the fact that this is self-contained.

What I would recommend however is to re-generate the `alire.toml` and `sqlite_ada.gpr` with the latest version of Alire:
`alr init --lib sqlite_ada`. 
We moved away from all the all the external variables (`SQLITE_COMPILE_CHECKS`, `SQLITE_RUNTIME_CHECKS`, `SQLITE_STYLE_CHECKS`, etc.) and now use a more simple and clear build switch system. 

I also recommend to avoid extra project files such as `example.gpr` because if another crate does the same `gprbuild` will complain about multiple projects having the same name and that makes the crate unusable. To provide examples it's better to make a "sub-crate" in your repo, like this for instance: https://github.com/wee-noise-maker/nael/tree/main/examples

**Comment by nytpu** [comment]
@Fabien-Chouteau
I'll work on making those changes this weekend.

I like to keep my libraries trivially usable outside of Alire but most of the changes recommended every time I submit a new library here are very incompatible with that goal; so I might look into doing a whole separate Alire release from a different branch…

**Comment by Fabien-Chouteau** [comment]
You can have a checked-in version of the config project file that will then be replaced by the Alire generated one for people using Alire. Like we do in here: https://github.com/alire-project/clic/blob/main/config/clic_config.gpr

Best of both worlds.

**Comment by mosteo** [comment]
Is this still in draft mode on purpose?

**Comment by nytpu** [comment]
@mosteo yeah, I've been busy with some projects and haven't been able to do the (rather substantial) changes needed. I'll competely close it and make a new one once it's ready.

**Pull request closed without merging**
