### PR TITLE
Add orka 1.0.0 crates

### PR DESCRIPTION
**Pull request by onox**

### CODE REVIEW

**Comment by mosteo** [comment]
I think this error is in our side to fix. Give me some time to diagnose.

**Comment by mosteo** [comment]
It should be fixed now. This new error

https://github.com/alire-project/alire-index/actions/runs/5014372934/jobs/9099241100#step:7:587

should be genuine.

**Comment by onox** [comment]
Windows is failing again:

```
 FETCHED SOURCE crate OK, deployed at orka_b455160b\orka_tensors_cpu
/d/a/alire-index/alire-index/orka_b455160b/orka_tensors_cpu /d/a/alire-index/alire-index
BUILD ENVIRONMENT
stderr: ALIRE.CHECKED_ERROR
stderr: Loading release from manifest: alire.toml
pins
orka_numerics
Pin path is not a valid directory: D:\a\alire-index\alire-index\orka_b455160b\orka_numerics
```

ubuntu-lts is apparently using Community instead of FSF.

**Comment by mosteo** [comment]
> Windows is failing again:

This is now fixed.

> ubuntu-lts is apparently using Community instead of FSF

No, but it is using a somewhat old gcc 10. You may want to add a minimum version for that.

**Review by Fabien-Chouteau — APPROVED** [review]

**Pull request merged**
