### PR TITLE
caught up with newest changes for HAL/RP2040

### PR DESCRIPTION
**Pull request by hgrodriguez**
including flash chip selection and linker switches

### CODE REVIEW

**Review by mosteo — DISMISSED** [review]
Hi, @hgrodriguez. I'm not sure why both `0.2.0` and `0.2.1` are being published? Is there any reason why `0.2.0` can't be skipped entirely?

**Comment by hgrodriguez** [comment]
@mosteo : you are right, but i was not sure how to skip 0.2.0 re-using my branch. I am more than happy to learn, else I will *always* delete my fork, and then re-raise the pull request so your world is clean. more than happy to make your life easier.

**Comment by mosteo** [comment]
It's enough to delete the file from the branch you're using to push the PR. I think in this case I can do it directly from the github interface so no need for you to worry.

**Review by mosteo — APPROVED** [review]

**Comment by hgrodriguez** [comment]
¡Muchas gracias!

**Pull request merged**
