### PR TITLE
Driver for SH1107/OLED 128x128 monochrome display

### PR DESCRIPTION
**Pull request by hgrodriguez**
This is an implementation for:
Driver for SH1107/OLED 128x128 monochrome display

### CODE REVIEW

**Comment by hgrodriguez** [comment]
it seems to fail, but this time at least not with line ending problems. 
What do I need to fix?

**Comment by mosteo** [comment]
My first guess is that your configuration treats warnings as errors. I don't remember how to disable that off the top of my head, but you may try to look in that direction. Or you may try to fix the warnings, if it's practical.

**Comment by hgrodriguez** [comment]
thanks for this. nevertheless, it builds on some platforms and not others. And yes, I do treat warnings as errors, I can promise you, that on my machine [macoS] there are no warnings which prevents the build.
I will check as much as I can.

**Comment by mosteo** [comment]
It's normal to get different results in our tests because we use an assortment of compilers; when a Linux distro packages a GNAT we use that one to see which experience users of the platform will get, besides we check with both the latest Community Edition and the latest Alire-supplied toolchain.

Probably it's safer from a forward-looking PoV to not enable "warnings as errors" for packaging, as newer GNATs tend to uncover more issues.

**Comment by hgrodriguez** [comment]
I am closing this pull request, as it needs modifications for the dependencies (embedded components -> adl_middleware).

**Pull request closed without merging**
