### PR TITLE
Adding the Lua scripting language

### PR DESCRIPTION
**Pull request by Patschkowski**
In the next step I want to make the Lua wrapper from AdaCore available to the Alire project

### CODE REVIEW

**Comment by mosteo** [comment]
Thanks for your contribution, @Patschkowski. As I see, this cratebuilds the plain `lua` executable. So, for dependents on the crate, this executable should be in the PATH. Thus, your manifest should include:
```
[environment]
PATH.prepend = "${CRATE_ROOT}/alire/build/bin"
```

**Comment by Patschkowski** [comment]
Integrated your proposal. Note, that for "alr publish" I have been using Alire on Linux as I am still seeing the same hang-up on Windows that I already reported.

**Review by mosteo — APPROVED** [review]

**Comment by mosteo** [comment]
Thanks. Yes, I still have to get around to reproduce https://github.com/alire-project/alire/issues/638, hope to do it soon.

**Comment by Fabien-Chouteau** [comment]
Hello @Patschkowski,
This is a pure C project that you can get from you distribution.

It doesn't fit into the Alire ecosystem which is a package manger for the Ada/SPARK language.

cc @mosteo

**Comment by mosteo** [comment]
This one has to be reverted then. @Patschkowski, if you need the `lua` executable as a dependency, you could propose an external that installs the appropriate system package. For example, we have already one for the lua devel library: https://github.com/alire-project/alire-index/blob/stable-0.4/index/li/liblua/liblua-external.toml

It's possible the bindings you wanted to provide indeed depend on `liblua`?

**Comment by Patschkowski** [comment]
I was not aware that there is also the option of external TOML files to get a package in your distribution installed - nice one. Does this also work on Windows? How to adjust that liblua-external.toml file to achieve something similar on Windows?

**Comment by Fabien-Chouteau** [comment]
> How to adjust that liblua-external.toml file to achieve something similar on Windows?

On Windows we use the msys2 ecosystem. The package `mingw-w64-x86_64-lua` seems to be the one you want.

See `libsdl` for example: https://github.com/alire-project/alire-index/blob/stable-0.4/index/li/libsdl2/libsdl2-external.toml

**Pull request merged**
