### PR TITLE
Add xoshiro 1.0.0

### PR DESCRIPTION
**Pull request by onox**

### CODE REVIEW

**Review by Fabien-Chouteau — APPROVED** [review]
Nice one @onox I was actually considering making this kind or pseudo RNG crate since I sometimes copy/paste the same crappy RNG code in my projects :+1: 

Did you consider making the package generic to instantiate with different unsigned types?
```ada
generic
   type T is mod <>;
package Xoshiro_Gen with SPARK_Mode => On is
```

**Comment by onox** [comment]
> Did you consider making the package generic to instantiate with different unsigned types?

A generic package would be great, but how exactly should it be implemented? Depending on the bit size of the type (32 or 64 bits) you need either the 128++ or 256++ version. They have 3 slightly different constants in procedure `Next`.

**Comment by Fabien-Chouteau** [comment]
> They have 3 slightly different constants in procedure `Next`.

I didn't see that...

**Comment by onox** [comment]
Basically have different instantiations at compile time, something like:

```ada
generic
   type T is mod <>;
package Xoshiro is
  (case T'Object_Size is
     when 32 => new Xoshiro_Gen (T, 7, 9, 11),
     when 64 => new Xoshiro_Gen (T, 23, 17, 45));
```

But I don't think Ada can do this at the moment :slightly_smiling_face:

**Comment by Fabien-Chouteau** [comment]
@onox Let's discuss in the repo :)

**Comment by Fabien-Chouteau** [comment]
@onox Let's discuss in the repo :)

**Pull request merged**
