### PR TITLE
Hgrodriguez edc client 1 3 2

### PR DESCRIPTION
**Pull request by hgrodriguez**

### CODE REVIEW

**Comment by mosteo** [comment]
Same issue as in #433

**Comment by hgrodriguez** [comment]
> Same issue as in #433

I am really sorry. I will fix this, not sure how to test, as access to windows is not easy.
I only come back when fixed.
I changed as instructed in  the .gitattributes documentation

**Comment by hgrodriguez** [comment]
> Same issue as in #433

@mosteo : I checked the failed windows build, and it is still using 1.3.1 version?
I was convinced I raised a pull request for version 1.3.2?

This is what windows fetched:
edc_client=1.3.1 successfully retrieved.

same for all environments.
Please give me a link where I understand, what I am doing wrong here, as I am convinced, that I requested edc-1.3.2:
https://github.com/hgrodriguez/edc-client/tree/1.3.2

and this is the link to my pull request:
https://github.com/hgrodriguez/alire-index/pull/3

**Comment by mosteo** [comment]
Actually it seems this PR contains manifests for both `1.3.1` and `1.3.2` (so both will be tested). I'll inspect your commit history to see what's happening and come back to you.

BTW, as long as one is not merged, you don't need to change versions (unless they are important somewhere else, of course).

**Comment by hgrodriguez** [comment]
thanks a lot and again sorry for wasting your time. I will ensure, that .gitattributes is in *any* repository from now on

**Comment by hgrodriguez** [comment]
do you want to reject this pull request and i raise a new one before you lose too much time?

**Comment by mosteo** [comment]
> do you want to reject this pull request and i raise a new one before you lose too much time?

If you have a clear view of the situation yes, go ahead with a new PR and I'll close the old ones. Otherwise it's OK, I haven't had the opportunity yet to look at it today.

**Comment by hgrodriguez** [comment]
> > do you want to reject this pull request and i raise a new one before you lose too much time?
> 
> If you have a clear view of the situation yes, go ahead with a new PR and I'll close the old ones. Otherwise it's OK, I haven't had the opportunity yet to look at it today.

please reject this PR. I will raise another one. Let me know (besides the .gitattributes which I added), what I have to fix. I will incorporate any feedback you have.

**Comment by mosteo** [comment]
OK, closing. The .gitattributes should be enough I expect.

**Pull request closed without merging**
