### PR TITLE
Ada Utility Library 2.6.0

### PR DESCRIPTION
**Pull request by stcarrez**
- update crates for the new version of Ada Utility Library
- convert the crates to use nested crates

### CODE REVIEW

**Comment by stcarrez** [comment]
The Debian and Fedora builds are failing due to AWS build which seems to fail on these targets:

```
src.gpr:39:37: "../.build/x86_64-pc-linux-gnu/setup/src" is not a valid directory
```

**Comment by mosteo** [comment]
Isn't https://github.com/alire-project/alire-index/actions/runs/5740141127/job/15587039913?pr=859#step:6:1213 part of the build of `utilada`?

**Comment by stcarrez** [comment]
> Isn't https://github.com/alire-project/alire-index/actions/runs/5740141127/job/15587039913?pr=859#step:6:1213 part of the build of `utilada`?

`utilada_aws` depends on `aws` which provides the `src.gpr` project which fails.  The `setup/src` directory is part of `aws`.

**Comment by stcarrez** [comment]
> Isn't https://github.com/alire-project/alire-index/actions/runs/5740141127/job/15587039913?pr=859#step:6:1213 part of the build of `utilada`?

It seems that AWS build don´t work very well in general:

* See aws 23.0.0: broken build on Fedora https://github.com/alire-project/alire/issues/1394
* The automated build skips the build on `utilada_aws` on Ubuntu 22.04 because it fails to resolve the correct GNAT 12 dependency (Ubuntu 22.04 and Debian 12 are my development platform so the project compiles)

I've removed the `utilada_aws` crate from the pull request to avoid blocking other crates.

Some notes I've collected on the automated build and issues.  The `archlinux` succeeds in building `utilada_aws` and dependencies are resolved into:

```
Dependencies (direct):
   aws~23.0
   utilada^2.6.0
Dependencies (solution):
   aws=23.0.0 (origin: source_archive)
   gnat=12.2.1 (gnat_external) (installed) (origin: external)
   gnatcoll=23.0.0 (origin: source_archive)
   libgpr=23.0.0 (origin: source_archive)
   make=4.4.0 (origin: system)
   openssl=3.0.8 (origin: system)
   utilada=2.6.0 (origin: git)
   xmlada=23.0.0 (origin: source_archive)
Dependencies (graph):
   aws=23.0.0        --> gnat=12.2.1 (gnat_external) (>=12)
   aws=23.0.0        --> gnatcoll=23.0.0 (~23.0.0)
   aws=23.0.0        --> make=4.4.0 (*)
   aws=23.0.0        --> openssl=3.0.8 (*)
   aws=23.0.0        --> xmlada=23.0.0 (~23.0.0)
   gnatcoll=23.0.0   --> libgpr=23.0.0 (~23.0.0)
   libgpr=23.0.0     --> gnat=12.2.1 (gnat_external) (/=2020)
   libgpr=23.0.0     --> xmlada=23.0.0 (~23.0.0)
   utilada_aws=2.6.0 --> aws=23.0.0 (~23.0)
   utilada_aws=2.6.0 --> utilada=2.6.0 (^2.6.0)
   xmlada=23.0.0     --> gnat=12.2.1 (gnat_external) (>=11)
UPDATING system repositories with sudo from user unset (0:-unset)...
pacman is /usr/sbin/pacman
warning: archlinux-keyring-20230225-1 is up to date -- reinstalling
resolving dependencies...
```

But, on Ubuntu 22.04, this fails miserably with:

```
Dependencies (direct):
   aws~23.0
   utilada^2.6.0
Dependencies (solution):
   aws=23.0.0 (origin: source_archive)
   gnatcoll=23.0.0 (origin: source_archive)
   libgpr=23.0.0 (origin: source_archive)
   make=4.3.0 (origin: system)
   openssl=3.0.2 (origin: system)
   utilada=2.6.0 (origin: git)
   xmlada=23.0.0 (origin: source_archive)
Dependencies (external):
   gnat((>=12) & (>=11)) & (/=2020) (indirect,hinted)
Dependencies (graph):
   aws=23.0.0        --> gnat>=12
   aws=23.0.0        --> gnatcoll=23.0.0 (~23.0.0)
   aws=23.0.0        --> make=4.3.0 (*)
   aws=23.0.0        --> openssl=3.0.2 (*)
   aws=23.0.0        --> xmlada=23.0.0 (~23.0.0)
   gnatcoll=23.0.0   --> libgpr=23.0.0 (~23.0.0)
   libgpr=23.0.0     --> gnat/=2020
   libgpr=23.0.0     --> xmlada=23.0.0 (~23.0.0)
   utilada_aws=2.6.0 --> aws=23.0.0 (~23.0)
   utilada_aws=2.6.0 --> utilada=2.6.0 (^2.6.0)
   xmlada=23.0.0     --> gnat>=11
Dependencies cannot be met
SKIPPING build for crate utilada_aws=2.6.0 with MISSING external dependencies
```

Given the above dependency list, it is not clear what version of GNAT is installed on the Ubuntu 22.04 automated build....

**Review by mosteo — APPROVED** [review]

**Comment by mosteo** [comment]
Thanks for the digging.  On Ubuntu 22.04, the native GNAT version is `10.5`.

**Pull request merged**
