### PR TITLE
GtkAda 24.0.0

### PR DESCRIPTION
**Pull request by Fabien-Chouteau**

### CODE REVIEW

**Comment by Fabien-Chouteau** [comment]
Hi @simonjwright, there is an issue during the configure step on MacPorts, are you able to check what's going on?

On Arch there's an issue with the installation of libgtk3.

**Comment by simonjwright** [comment]
The arch problem, there was a corrupt package issue at line 503 in the log?

The macports problem, [this line](https://github.com/alire-project/alire-index/blob/9fa62dbe95e31f2a7425b475e1adffa644c88344/index/gt/gtkada/gtkada-24.0.0.toml#L19) references mingw!

**Comment by Fabien-Chouteau** [comment]
> The macports problem, [this line](https://github.com/alire-project/alire-index/blob/9fa62dbe95e31f2a7425b475e1adffa644c88344/index/gt/gtkada/gtkada-24.0.0.toml#L19) references mingw!

Indeed, but that shouldn't be a problem. I added macport and homebew entries to the `pkg_config-external` crate, that solved the first problem. Now there's an issue with an include:
```
gtkada_24.0.0_80c56171/src/misc_osx.m:37:10: fatal error: 'gdk/gdkquartz.h' file not found
#include <gdk/gdkquartz.h>
         ^~~~~~~~~~~~~~~~~
```
On Arch there's an issue with a package signature in pacman. I don't think we can do something about this.

@mosteo if you are ok I suggest merging this to not penalize the other platforms.

**Comment by mosteo** [comment]
The Arch issue was a matter of outdated Docker. I'm going to merge and we can update if there's a fix for the macOS issue.

**Review by mosteo — APPROVED** [review]

**Comment by simonjwright** [comment]
I’m not sure there is a macOS issue? I just built successfully (before the gtkada-24.0.0 branch got deleted!)

I have `/opt/homebrew/Cellar/gtk+3/3.24.38/include/gtk-3.0/gdk/gdkquartz.h`

**Comment by mosteo** [comment]
As we are seeing in https://github.com/alire-project/alire-index/pull/1068 the error in Arch persists (in both v23 and 24)

**Pull request merged**
