### PR TITLE
6502 tutorial module atari_atr_tools release 1.1.0

### PR DESCRIPTION
**Pull request by krischik**
* Update to current AdaCL
* Add AUnit Tests

### CODE REVIEW

**Comment by krischik** [comment]
Why where the build canceled?

**Comment by mosteo** [comment]
Builds are cancelled when another check in the same workflow fails. You can push fixes and they'll all retrigger.

**Comment by krischik** [comment]
> Builds are cancelled when another check in the same workflow fails. You can push fixes and they'll all retrigger.

Line 54 is correct:

```
[build-switches]
development.runtime_checks  = "Overflow"
release.runtime_checks      = "Default"
validation.runtime_checks   = "Everything"
development.contracts       = "Yes"
release.contracts           = "No"
validation.contracts        = "Yes"
```

But it's also the only option with a `.` in the name.

**Comment by krischik** [comment]
The pins from the test cases need to be removed manually. Close at this needs a hot-fix with new tar-file.

**Comment by mosteo** [comment]
> Line 54 is correct:

Yes, that's a different problem. The check-author workflow can't cope with some more recent TOML syntax, so that workflow failing shouldn't be a concern. It also won't cause the cancellation of the rest. The other jobs that do build the crate are aborted when other in the same workflow batch fails.

**Pull request closed without merging**
