### PR TITLE
SDLAda-2.5.5 release

### PR DESCRIPTION
**Pull request by Lucretia**
Latest revision update to 2.5.5.

### CODE REVIEW

**Comment by Lucretia** [comment]
This is failing due to alire errors:

```

stderr: CONSTRAINT_ERROR
stderr: alire-conditional_trees-case_nodes.adb:178 range check failed
stderr: raised CONSTRAINT_ERROR : alire-conditional_trees-case_nodes.adb:178 range check failed
[/home/runner/work/alire-index/alire-index/alire_install/bin/alr]
0xca7590 Alire.Toml_Load.Dependency_Loader.Case_Nodes.Leaf_Count.2Xnb at alire-conditional_trees-case_nodes.adb:178
```

**Comment by mosteo** [comment]
Sorry for the trouble with msys2, which is not caused by your crate. The fix will be coming shortly.

**Comment by Lucretia** [comment]
> Sorry for the trouble with msys2, which is not caused by your crate. The fix will be coming shortly.

ok.

**Comment by mosteo** [comment]
The problem with the Windows toolchain is solved. The current error is unrelated, @Lucretia.

**Comment by Lucretia** [comment]
> The problem with the Windows toolchain is solved. The current error is unrelated, @Lucretia.

Says the distribution is msys2, I have the depends in place for libsdl2* libs which have entries for msys2, but the compiler is failing to find ```SDL_ttf.h``` and ```SDL_image.h```.

**Comment by Fabien-Chouteau** [comment]
@Lucretia This is why we have this:
```
[environment.'case(distribution)'.msys2.C_INCLUDE_PATH]
# sdlada expects SDL2 headers to be in the C_INCLUDE_PATH but the option
# used in the project file ("-I/usr/include/SDL2") doesn't work with msys2
append = "${DISTRIB_ROOT}/mingw64/include/SDL2"
```
in the alire.toml of `2.5.4`: https://github.com/alire-project/alire-index/blob/stable-1.2.1/index/sd/sdlada/sdlada-2.5.4-1.toml

**Comment by Fabien-Chouteau** [comment]
Note that if we manage to add `pkg-config` support in Alire we won't have to do this anymore.

**Comment by Lucretia** [comment]
> @Lucretia This is why we have this:
> 
> ```
> [environment.'case(distribution)'.msys2.C_INCLUDE_PATH]
> # sdlada expects SDL2 headers to be in the C_INCLUDE_PATH but the option
> # used in the project file ("-I/usr/include/SDL2") doesn't work with msys2
> append = "${DISTRIB_ROOT}/mingw64/include/SDL2"
> ```
> 
> in the alire.toml of `2.5.4`: https://github.com/alire-project/alire-index/blob/stable-1.2.1/index/sd/sdlada/sdlada-2.5.4-1.toml

Thanks. I;'ll add it until I can fix my gpr, I did look at the msys package contents, wasn't sure if that is what the problem was, msys used to have a /usr that everything went into.

**Comment by Lucretia** [comment]
Ok, all passing.

**Review by Fabien-Chouteau — APPROVED** [review]

**Comment by Lucretia** [comment]
Thanks.

**Pull request merged**
