### PR TITLE
Add Dotenv 1.0.0

### PR DESCRIPTION
**Pull request by Heziode**

### CODE REVIEW

**Comment by Heziode** [comment]
No that the first commit failed because of `maintainers-logins ` in `alire.toml`, that is case-sensitive.
This information is not indicate in the [docs](https://alire.ada.dev/docs/).

**Comment by mosteo** [comment]
Thanks for the report, Heziode.

**Comment by Heziode** [comment]
@mosteo I created an issue for this problem: https://github.com/alire-project/alire/issues/663

**Review by mosteo — APPROVED** [review]

**Comment by Heziode** [comment]
@mosteo you have approved the PR, but it is not merged. Is it an oversight or is there something missing?

**Comment by mosteo** [comment]
My fault. Merged, thanks.

**Pull request merged**
