### PR TITLE
Add various project from Gautier de Montmollin

### PR DESCRIPTION
**Pull request by Fabien-Chouteau**
Hi @zertovitch, I am adding couple of your project in the `Alire` index.

As far as I can see there is no modification required so I just use the archives hosted on sourceforge.

I added your login in the list of maintainers so you will be able to update the TOML files yourself in the future. You can update maintainer email if you want to.

### CODE REVIEW

**Comment by zertovitch** [comment]
Thx, the .toml's look good (latest versions of releases). Is there a way I could help, or should I wait for the merge for quick tests?

**Comment by Fabien-Chouteau** [comment]
> Is there a way I could help, or should I wait for the merge for quick tests?

You can checkout the branch on my fork and declare a local index `alr index --add=/path/to/checkout/ -name=my_index`.

**Comment by zertovitch** [comment]
Just tested successfully GID.
`alr init --bin gid_test
16:25:32 ~/alire_test $cd gid_test/`

A little detail: the `gid_test.toml` created is like this:
```["0.0.0"]
origin = "file://.."
["0.0.0".depends-on]
gid = [
"any",
"any",
]
[general]
description = "Shiny new project"
maintainers = [
"your@email.here",
]
maintainers-logins = [
"github-username",
]
```
**but** subsequent commands like `alr build` issue this:
```
ERROR: Cannot continue with invalid session: Failed to load /home/gautier/alire_test/gid_test/alire/gid_test.toml: dependency version must be a string
ERROR: alr build unsuccessful
```
which is easy to fix by replacing
```
gid = [
"any",
"any",
]
```
by `gid = "any"`.

Otherwise, all good!
A cool thing could be to pass arguments to the program when doing `alr run`.
```
16:36:52 ~/alire_test/gid_test $alr run git_test Photo0935.jpg 
Too many arguments
16:38:00 ~/alire_test/gid_test $alire/build/bin/gid_test Photo0935.jpg 
Processing Photo0935.jpg...
.........v.........v
********************
```
It would save the need to write `alire/build/bin/gid_test` for running the program with arguments.

**Comment by mosteo** [comment]
Thanks for the feedback.

> A cool thing could be to pass arguments to the program when doing `alr run`

Can you try the -a argument (see `alr run -h`)? I'm not in a dev computer right now.

**Comment by zertovitch** [comment]
Ow, I was off track anyway with the `alr run gid_test` syntax... So the correct command is `alr run -a Photo0935.jpg` and works correctly. Perhaps a message like "Too many arguments. Try ""alr run -h"" for help" could help the lost souls...

**Comment by zertovitch** [comment]
Success with the Bar_Codes. This time I did things obviously more straightforward and the issue with the dependencies syntax did not pop up.
However, if I do accidentally (when everything builds and runs smoothly): `alr with bar_codes` I get again the extra "any" in `abc_test.toml`.
When I put back `bar_codes = "any"` I can run again `alr build` and `alr run` successfully.
If I run `alr run` just after editing `abc_test.toml` (even just adding a space) I get `ERROR: alr run unsuccessful`, but the sequence `alr build` and `alr run` is successful.

**Comment by mosteo** [comment]
Thanks for your tests, @zertovitch . The problems you report may be related to bug alire-project/alire#310, but in any case when I address that I'll make sure your problems go away too.

**Comment by zertovitch** [comment]
Cool!
Regarding `apdf.toml`, the project has a copy of GID for embedding images in PDF documents.
Obviously, in the context of Alire, we should have rather (1) a dependency on the GID crate, and (2) an extra `pdf_alire.gpr` with at least the "gid" subdirectory removed in `for Source_Dirs use (".", "gid", "demo", "tools", "test");`.
I can take care of (2).
For (1), how should we add a dependency properly? I guess something very similar to `["0.0.0".depends-on] gid = "any"` ?
Is 0.0.0 correct in this context?

**Comment by pmderodat** [comment]
Hello @zertovitch and thank you for having a look!
> For (1), how should we add a dependency properly? I guess something very similar to `["0.0.0".depends-on] gid = "any"` ?
> Is 0.0.0 correct in this context?

No, it should be the release of apdf that depends on GID, so `5.0.0` if I understand correctly: it’s the version of the release that this PR registers. Also, make sure you specify a version constraint on the GID dependency: we don’t know what the future is made of, so you can’t say today that apdf `5.0.0` will be compatible with any future version of `GID`. :-) Assuming it’s compatible with GID versions `9.*` (i.e. any version whose major number is 9), this would be:
```
['5.0.0'.depends-on]
gid = "^9.0.0"
```

**Pull request merged**
