### PR TITLE
utilada=2.1.0: Constraints on compiler

### PR DESCRIPTION
**Pull request by jquorning**
Also fix readthedocs url in long-description.

### CODE REVIEW

**Comment by jquorning** [comment]
Actually I do not know if utilada compiles with CE2021 or later.

**Review by mosteo — APPROVED** [review]

**Comment by mosteo** [comment]
> Actually I do not know if utilada compiles with CE2021 or later.

Given that CE is discontinued and we don't test with it anymore, let's go with it.

**Comment by jquorning** [comment]
Guess it should have been "<11" instead of "<=10"..?

https://github.com/alire-project/alire-index/runs/7597046662#step:9:404

**Comment by mosteo** [comment]
Oh right, as `<=10` will be interpreted as `<=10.0.0`... leaving out all of `^10`

**Pull request merged**
