### PR TITLE
sdlada 2.5.19

### PR DESCRIPTION
**Pull request by Lucretia**
Created via `alr publish` with `alr 2.0-beta1`

### CODE REVIEW

**Comment by Fabien-Chouteau** [comment]
Hi @Lucretia , the sdl2_mixer dependency is missing, you have to rebase this change on top of the sdl2_mixer patch.

**Comment by Lucretia** [comment]
I don't know how. Where does alire store the index it uses to create the branch?

**Comment by Lucretia** [comment]
Do I just do an ```alr publish``` again once I rebase onto the alire-index branch? I thought I'd created a new branch for this, but I don't seem to have it.

**Comment by Lucretia** [comment]
I have rebased it on that patch.

**Comment by Fabien-Chouteau** [comment]
```
ERROR:    case(distribution):
invalid enumeration value: homebrew
```
Alire 1.2.2 doesn't know about howbrew and macports distribs.
I think you have to remove those until we get the 2.0 release.

**Comment by Lucretia** [comment]
Well, I don't know how this is supposed to work for macos then.

**Comment by Lucretia** [comment]
@simonjwright I take it your mac repo is for v2? You'll need to uncomment the lines for yours.

**Comment by simonjwright** [comment]
When are we likely to get the v2 release? It’s 3 months since the beta1 release ...

We may be able to work round this, but for a start we need to restore this in gpr-set-externals:
```
macos = { SDL_PLATFORM = "macosx" }
```

This worked for me:

1. Tell Mac users to install Homebrew and then sdl2, sdl2_image, sdl2_ttf, sdl2_mixer
2. Put this in ~/.bash_profile (or equivalent for zsh):
```
eval $(/opt/homebrew/bin/brew shellenv)
export C_INCLUDE_PATH=$HOMEBREW_PREFIX/include
export CPLUS_INCLUDE_PATH=$HOMEBREW_PREFIX/include
export LIBRARY_PATH=$HOMEBREW_PREFIX/lib
```
(/usr/local/bin/shellenv if it’s an x86_64 mac)
3. `alr build -- -cargs:c -DSDL_HOMEBREW=1`

**Comment by simonjwright** [comment]
> @simonjwright I take it your mac repo is for v2? You'll need to uncomment the lines for yours.

Thanks for the reminder!

**Comment by Lucretia** [comment]
@simonjwright So I take it that the current problems are not *my* problem to fix here then? Is it worth adding the [framework](https://wiki.libsdl.org/SDL2/FAQMacOSX) version as well?

Re v2: I have to agree, having 2 incompatible ways of handling this is annoying.

**Comment by simonjwright** [comment]
As far as macOS is concerned, it’s notable that the runner comes with Homebrew pre-installed, and alire knows to install the HB versions of the SDL2 libraries - so it has to be using Alire v2.

In fact, we can see it [here](https://github.com/alire-project/alire-index/actions/runs/7411444595/job/20165998164?pr=952#step:6:44).

So why is there a problem with the `alire.toml`?

(I can see that we want to avoid problems for people just beginning on their Alire journey (!!), but this does seem inconsistent).

**Comment by simonjwright** [comment]
The Windows problem looks like a mistaken include path.

**Comment by Lucretia** [comment]
> The Windows problem looks like a mistaken include path.

I'm trying it locally, had to reinstall to get the thing to compile.

Now, the libSDL2* stuff installs to ```/mingw64/```, but I've no clue how alire works on windows as the installer creates a link to powershell, fine can use that, can run ```alr build```, but I don't think / is the msys root, it is if I run bash first.

So, does the github action start bash, I can't see it if it does.

the ```sdl2-config --cflags``` returns

```
-IC:/Users/laguest/.cache/alire/msys64/mingw64/include/SDL2 -Dmain=SDL_main
```

Obviously, I can't hard code that. Ideally, I would add the following to the gpr:

```
         when "windows" =>
            C_Switches   := C_Switches & ("-I/mingw64/include/SDL2");

         when others =>
```

So, something has changed in msys2 since the last time.

**Comment by Lucretia** [comment]
Yeah, I don't know how to fix this. I need some assistance on how the gnat_native is built and used by alire.

**Comment by simonjwright** [comment]
So as to check what’s going on here, I faked up my own 2.5.6 version (using the 2.5.5. origin; I swear to delete all trace of this!!) and the windows-latest job succeeded.

The libsdl2* externals downloaded were the same (except for mixer): [mine](https://github.com/simonjwright/alire-index/actions/runs/7420153888/job/20190988652?pr=2#step:6:438), [this PR](https://github.com/alire-project/alire-index/actions/runs/7411444595/job/20165999080?pr=952#step:6:417).

I also tried a [2.5.20](https://github.com/simonjwright/alire-index/pull/2) version (2.5.19 + 1), the *-dev runs succeeded (including the Windows one).

**Comment by Lucretia** [comment]
Does yours install SDL2 to ```/usr```? Because on my laptop it installs to ```msys/mingw64``` (this is / for this install) and I suspect it does for the failure above. There is literally nothing in my ```/usr/{bin,include,lib}``` dirs.

@Fabien-Chouteau Any idea?

**Comment by simonjwright** [comment]
With my experimental 2.5.20, in the [alr dev/windows latest run](https://github.com/simonjwright/alire-index/actions/runs/7424721138/job/20204931381?pr=2) (dev => using latest development alr), the [C_INCLUDE_PATH](https://github.com/simonjwright/alire-index/actions/runs/7424721138/job/20204931381?pr=2#step:6:656) is `C_INCLUDE_PATH="C:\Users\runneradmin\.cache\alire\msys64\mingw64\include;C:\Users\runneradmin\.cache\alire\msys64/mingw64/include/SDL2"` and [LIBRARY_PATH](https://github.com/simonjwright/alire-index/actions/runs/7424721138/job/20204931381?pr=2#step:6:660) is `export LIBRARY_PATH="C:\Users\runneradmin\.cache\alire\msys64\mingw64\lib"`.

I see `msys64`, you quote `msys` - is that significant?

**Comment by Lucretia** [comment]
> With my experimental 2.5.20, in the [alr dev/windows latest run](https://github.com/simonjwright/alire-index/actions/runs/7424721138/job/20204931381?pr=2) (dev => using latest development alr), the [C_INCLUDE_PATH](https://github.com/simonjwright/alire-index/actions/runs/7424721138/job/20204931381?pr=2#step:6:656) is `C_INCLUDE_PATH="C:\Users\runneradmin\.cache\alire\msys64\mingw64\include;C:\Users\runneradmin\.cache\alire\msys64/mingw64/include/SDL2"` and [LIBRARY_PATH](https://github.com/simonjwright/alire-index/actions/runs/7424721138/job/20204931381?pr=2#step:6:660) is `export LIBRARY_PATH="C:\Users\runneradmin\.cache\alire\msys64\mingw64\lib"`.

How do you get it to dump the ```C_INCLUDE_PATH``` var? I don't see it in the logs below.

> 
> I see `msys64`, you quote `msys` - is that significant?

no, just because it's been years since i used it.

**Comment by simonjwright** [comment]
> > With my experimental 2.5.20, in the [alr dev/windows latest run](https://github.com/simonjwright/alire-index/actions/runs/7424721138/job/20204931381?pr=2) (dev => using latest development alr), the [C_INCLUDE_PATH](https://github.com/simonjwright/alire-index/actions/runs/7424721138/job/20204931381?pr=2#step:6:656) is `C_INCLUDE_PATH="C:\Users\runneradmin\.cache\alire\msys64\mingw64\include;C:\Users\runneradmin\.cache\alire\msys64/mingw64/include/SDL2"` and [LIBRARY_PATH](https://github.com/simonjwright/alire-index/actions/runs/7424721138/job/20204931381?pr=2#step:6:660) is `export LIBRARY_PATH="C:\Users\runneradmin\.cache\alire\msys64\mingw64\lib"`.
> 
> How do you get it to dump the `C_INCLUDE_PATH` var? I don't see it in the logs below.
> 
> > I see `msys64`, you quote `msys` - is that significant?
> 
> no, just because it's been years since i used it.

It’s at [line 689](https://github.com/alire-project/alire-index/actions/runs/7411444595/job/20165999080?pr=952#step:6:690) ... without the `/SDL2` ... oh, it’s there because of [line 281](https://github.com/simonjwright/alire-index/actions/runs/7424721138/job/20204931381?pr=2#step:6:282), which is there because of [this in 2.5.5](https://github.com/Lucretia/alire-index/blob/353f2fe7845654866c3c8ba9fc1eab3a559511f3/index/sd/sdlada/sdlada-2.5.5.toml#L40),  which I managed to include in my bodged-up 2.5.20 but which isn’t in your 2.5.19:
```
[environment.'case(distribution)'.msys2.C_INCLUDE_PATH]
# sdlada expects SDL2 headers to be in the C_INCLUDE_PATH but the option
# used in the project file ("-I/usr/include/SDL2") doesn't work with msys2
append = "${DISTRIB_ROOT}/mingw64/include/SDL2"
```

**Comment by Lucretia** [comment]
Thanks, I've no clue where that append came from, it's not in my local history at all, I checked out v2.5.5 and v2.5.6 and it's not in the toml. I'm assuming I should add that to my ```sdlada/alire.toml``` file, it shouldn't be auto added by ```alr``` right?

And we're still expecting MacOS to fail, right?

**Comment by simonjwright** [comment]
Looks as though it was added in f92f8dae (2.3.1) by Alejandro. Perhaps you haven’t been syncing your `alr-index` fork?

As far as I know, the alire.toml in your sdlada is only used when building sdlada on its own (during development): if someone says `alr with sdlada` they get the code _without_ an alire.toml, using the one from the index. But ofc the one from the index is derived from the one in the repo during alr publish (not sure whether everyone sticks by that rule!)

At the moment, the macOS tests fail because the version_*.c files all use the framework includes (e.g. `<SDL2_ttf/SDL_ttf.h>`) if neither Homebrew nor MacPorts is present. But it doesn’t look to me as though there are any framework switches (`-F`, `-framework`) anywhere, so should the framework includes be retired?

(because of the way our compilers are built, `/Library/Frameworks` isn’t included in search paths unless specified with `-F /Library/Frameworks`)

**Comment by Lucretia** [comment]
> Looks as though it was added in [f92f8da](https://github.com/alire-project/alire-index/commit/f92f8dae348124f673b128d79902a30a206a8a80) (2.3.1) by Alejandro. Perhaps you haven’t been syncing your `alr-index` fork?

Really should've been added via the sdlada repo and pr'd there, then it would be included in the next releases.
 
> As far as I know, the alire.toml in your sdlada is only used when building sdlada on its own (during development): if someone says `alr with sdlada` they get the code _without_ an alire.toml, using the one from the index. But ofc the one from the index is derived from the one in the repo during alr publish (not sure whether everyone sticks by that rule!)
> 
> At the moment, the macOS tests fail because the version_*.c files all use the framework includes (e.g. `<SDL2_ttf/SDL_ttf.h>`) if neither Homebrew nor MacPorts is present. But it doesn’t look to me as though there are any framework switches (`-F`, `-framework`) anywhere, so should the framework includes be retired?

I don't know. It might be worth having the option to install the frameworks and build, but the alire stuff would need a way to get the frameworks on the test server action thingy.
 
> (because of the way our compilers are built, `/Library/Frameworks` isn’t included in search paths unless specified with `-F /Library/Frameworks`)

Way back when I started this, I did have it building with the sdl2 framework, but that was way before alire.

**Comment by simonjwright** [comment]
I made a PR on sdlada, see what you think (NB, taking account of your remarks above about proper procedure for PRs :-)

**Comment by Lucretia** [comment]
Thanks @simonjwright. I've had to create a new release because it needed changed in the source, not just the toml. #959 is the new one, @Fabien-Chouteau.

**Pull request closed without merging**
