### PR TITLE
Gnat fsf 12 2

### PR DESCRIPTION
**Pull request by Fabien-Chouteau**

### CODE REVIEW

**Comment by Fabien-Chouteau** [comment]
@mosteo I think this is exhausting the available disk space on Windows...

**Comment by mosteo** [comment]
> @mosteo I think this is exhausting the available disk space on Windows...

Indeed. We'll need to do some cleanup in between tests. I'll take care of it.

**Comment by mosteo** [comment]
It's fixed now.

**Review by mosteo — APPROVED** [review]

**Comment by mosteo** [comment]
Is this one ready for merge, @Fabien-Chouteau ?

**Comment by Fabien-Chouteau** [comment]
Yes we can go ahead.

**Pull request merged**
