### PR TITLE
qplt 20230720.0.0

### PR DESCRIPTION
**Pull request by bracke**
Created via `alr publish` with `alr 2.0.1`

### CODE REVIEW

**Comment by bracke** [comment]
It seems to complain about ssl. But only on some platforms?

**Comment by mosteo** [comment]
> It seems to complain about ssl. But only on some platforms?

In those not failing, something is requesting the linking to those things in some undeclared way. The proper thing for the Alire index, though, is that the first dependency requiring `ssl` declares explicitly the dependency on the external library. I'm not sure which one is though, I see `libtls` in the index, but I also see `aws` depending on `openssl`.

**Comment by bracke** [comment]
The project only depends on Ada_Gui and PragmARC.
AdaGui depends on SimpleComponents but also GNAT.Sockets (referenced & used in the code).

Could GNAT.Sockets be the culprit?

**Comment by mosteo** [comment]
> The project only depends on Ada_Gui and PragmARC. AdaGui depends on SimpleComponents but also GNAT.Sockets (referenced & used in the code).
> 
> Could GNAT.Sockets be the culprit?

From that list, the likely culprit looks to me to be `simple_components`. But it's strange, since it depends on `libgnutls`, which should be pulling in any needed system dependency.

Let me do a test, I will push to your branch.

**Review by mosteo — APPROVED** [review]

**Comment by mosteo** [comment]
Indeed adding a dependency on `ssl` fixes it.

**Pull request merged**
