### PR TITLE
labs_solar_system 1.1.0

### PR DESCRIPTION
**Pull request by leogermond**
Created via `alr publish` with `alr 2.0.1`

### CODE REVIEW

**Comment by leogermond** [comment]
On MacOS

`https://github.com/alire-project/alire-index/actions/runs/9550090925/job/26321239589?pr=1091#step:7:595` @mosteo is it possible that the MacOS 12 build is not working for libSDL2?

**Comment by leogermond** [comment]
As for Fedora
```
Dependencies (tree):
   mage=0.6.1 (~0.6.1)
   +-- sdlada=2.5.20 (^2.5.4-1)
       +-- libsdl2^2.0.0 (indirect,hinted) (^2.0.0)
       +-- libsdl2_image^2.0.0 (indirect,hinted) (^2.0.0)
       +-- libsdl2_mixer^2.0.0 (indirect,hinted) (^2.0.0)
       +-- libsdl2_ttf^2.0.0 (indirect,hinted) (^2.0.0)
       +-- make=4.4.1 (*)
Dependencies cannot be met
Warning: Spent 0.36 seconds exploring complete solutions
Warning: Exploring incomplete solutions to dependencies, this may take some time...
UPDATING system repositories with sudo from user unset (0:-unset)...
FAIL: crate labs_solar_system=1.1.0 dependencies cannot be met
Note: you can either fix dependencies or use the `available`
      property to exclude platforms with missing dependencies.
Error: Error: stdout /home/runner/work/alire-index/alire-index/alire-index-checks/scripts /home/runner/work/alire-index/alire-index
```
Is that also related to libSDL2 support?

**Comment by mosteo** [comment]
Yup, Fedora/CentOS don't have external definitions for libsdl2. That might be easily fixable, let me try.

As for macOS... The problem certainly seems to be in the SDL crate itself.

**Comment by mosteo** [comment]
Nothing that you have to do right now, if it wasn't clear.

**Comment by mosteo** [comment]
Fedora and CentOS OK, the SDL2 trouble will be harder to diagnose so I'm merging already.

**Pull request merged**
