### PR TITLE
Add macOS support to GTKAda 21.0.0.

### PR DESCRIPTION
**Pull request by Blady-Com**
Tested with GTK3 from MacPorts.

### CODE REVIEW

**Comment by Blady-Com** [comment]
It seems that the remaining errors are no longer from my modifications.
How to go further?

**Comment by mosteo** [comment]
Hi @Blady-Com , I'm traveling this week, I'll be able to take a look at this after I return, thanks for your patience.

**Comment by mosteo** [comment]
For the failure in Arch, it would seem that more dependencies are required. For the time being, I would simply disable availability for this distro.

And for windows, it seems this release has never worked. It could be disabled too. 

I will add these changes to your branch.

**Review by Fabien-Chouteau — APPROVED** [review]

**Comment by Blady-Com** [comment]
The merge was against stable-1.2 branch.
How is the best way to bring it to stable-1.2.1?

**Comment by mosteo** [comment]
I didn't realize, I've cherry picked it so it's now in 1.2.1

**Pull request merged**
