### PR TITLE
Add Ada Web Application 2.1.0 crates

### PR DESCRIPTION
**Pull request by stcarrez**
I've made a new release of AWA and this pull request provides two crates for AWA.

awa: the main AWA framework
awa_unit: a unit testing framework for AWA applications

### CODE REVIEW

**Comment by mosteo** [comment]
The current error is on my side of things, Stephane. I will fix it soon.

**Comment by Fabien-Chouteau** [comment]
Hello @stcarrez, we are sorry that this PR got left behind.

I tried to use the awa crate here but all the depencencies require versions that are not in the index (ado, utilada, etc.).

**Comment by Fabien-Chouteau** [comment]
@stcarrez I updated the releases for Alire 1.0, the patch is here: https://github.com/Fabien-Chouteau/alire-index/commit/99d6ad41845e57081eab3e9805f5c693459192c7
Feel free to use it for a new PR.

BTW I could not compile everything, what GNAT version are you using?

**Comment by mosteo** [comment]
This PR should be reopened against the `stable-1.2` branch, which is the current stable. In my experience it is not enough to rebase and change the base branch, due to some limitation in the Github actions framework, so I'm closing it now. Sorry for the inconvenience.

**Pull request closed without merging**
