### PR TITLE
ZipDCF 2.0.2

### PR DESCRIPTION
**Pull request by onox**

### CODE REVIEW

**Comment by Fabien-Chouteau** [comment]
The macOS toolchain installation failed. I don't think this is blocking.

**Review by Fabien-Chouteau — DISMISSED** [review]

**Comment by mosteo** [comment]
Turns out, the macOS build is failing with some linker error...

**Comment by onox** [comment]
I'll remove these flags from zipdcf.gpr.

**Comment by onox** [comment]
All systems GO! :wink:

**Review by mosteo — APPROVED** [review]

**Pull request merged**
