### PR TITLE
AWS 23.0

### PR DESCRIPTION
**Pull request by reznikmm**

### CODE REVIEW

**Comment by Fabien-Chouteau** [comment]
Link error on Windows:
```
c:/users/runneradmin/.config/alire/cache/dependencies/gnat_native_12.2.1_c210a022/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:\a\alire-index\alire-index\aws_23.0.0_6c406859\.build\x86_64-w64-mingw32\release\relocatable\obj\src\aws-net-websocket.o:aws-net-websocket.adb:(.text+0x639): undefined reference to `gnatcoll__refcount__finalize'
```

Of course it works on my machine...

**Comment by Fabien-Chouteau** [comment]
Build failure on Fedora.

I don't know why `pacman` shows up in the results here since this is Fedora...

`src.gpr:97:37: "../.build/x86_64-linux-gnu/setup/src" is not a valid directory` might be a consequence of  an error in the setup phase.

```
ERROR: Command ["gprbuild", "-s", "-j0", "-p", "-P", "/home/runner/work/alire-index/alire-index/aws_23.0.0_6c406859/aws.gpr"] exited with code 4
ERROR: Compilation failed.
, stderr sudo: pacman: command not found
sudo: pacman: command not found
make[1]: which: No such file or directory
make[1]: which: No such file or directory
make[1]: which: No such file or directory
make[1]: which: No such file or directory
make[1]: which: No such file or directory
make[1]: which: No such file or directory
src.gpr:97:37: "../.build/x86_64-linux-gnu/setup/src" is not a valid directory
gprbuild: "/home/runner/work/alire-index/alire-index/aws_23.0.0_6c406859/aws.gpr" processing failed
stderr: Command ["gprbuild", "-s", "-j0", "-p", "-P", "/home/runner/work/alire-index/alire-index/aws_23.0.0_6c406859/aws.gpr"] exited with code 4
stderr: ALIRE.CHECKED_ERROR
stderr: Command ["gprbuild", "-s", "-j0", "-p", "-P", "/home/runner/work/alire-index/alire-index/aws_23.0.0_6c406859/aws.gpr"] exited with code 4
stderr: raised ALIRE.CHECKED_ERROR : alire-stored-error:1
[/usr/bin/alr]
0xd7ab1a Alire.Raise_Checked_Error at alire.adb:251
0xa4211b Alire.Os_Lib.Subprocess.Checked_Spawn at alire-os_lib-subprocess.adb:110
0xc5cb66 Alire.Spawn.Command at alire-spawn.adb:21
0xc5d294 Alire.Spawn.Gprbuild at alire-spawn.adb:41
0xbc12c8 Alire.Roots.Build.Build_Single_Release.Call_Gprbuild at alire-roots.adb:140
0xbbf927 Alire.Roots.Build.Build_Single_Release at alire-roots.adb:171
0xbdb6d6 Alire.Roots.Traverse.Traverse_Wrap at alire-roots.adb:1364
0xc25803 Alire.Solutions.Traverse.Visit at alire-solutions.adb:1443
0xc2441a Alire.Solutions.Traverse at alire-solutions.adb:1518
0xbdb824 Alire.Roots.Traverse at alire-roots.adb:1368
0xbbfcb8 Alire.Roots.Build at alire-roots.adb:196
0x4a0334 Alr.Commands.Build.Execute at alr-commands-build.adb:58
0x4a01d9 Alr.Commands.Build.Execute at alr-commands-build.adb:34
0x53bb7e Alr.Commands.Sub_Cmd.Execute at clic-subcommand-instance.adb:742
0x54756f Alr.Commands.Execute at alr-commands.adb:492
0x43cb1a Alr.Main at alr-main.adb:10
0x43f3e7 Main at b__alr-main.adb:2132
[/lib64/libc.so.6]
0x7f703e26558e
0x7f703e265647
[/usr/bin/alr]
0x43c9f8 _start at ???
0xfffffffffffffffe
```

**Comment by mosteo** [comment]
> I don't know why `pacman` shows up in the results here since this is Fedora...

This is a spurious message. In order not to have complex logic about the applicable package manager we're trying them all.

It seems to build OK now, except for macOS where `openssl` is missing.

**Comment by mosteo** [comment]
liblzma seems to have creeped in but that would be a minor non-issue.

**Review by mosteo — DISMISSED** [review]

**Comment by mosteo** [comment]
OK to merge without macOS?

**Comment by Fabien-Chouteau** [comment]
ok for me

**Comment by reznikmm** [comment]
ok for me too

**Comment by reznikmm** [comment]
I've added
```yaml
[gpr-set-externals]
PRJ_LDAP="Disabled"
```

because it tries to link LDAP library.

Please review again.

**Review by mosteo — APPROVED** [review]

**Pull request merged**
