### PR TITLE
spoon 1.0.0

### PR DESCRIPTION
**Pull request by onox**

### CODE REVIEW

**Comment by onox** [comment]
This PR can wait until next release of Alire.

**Comment by onox** [comment]
@mosteo One of the VMs is hanging

**Comment by mosteo** [comment]
There's something funny going on as it always hangs in the same point.

**Comment by mosteo** [comment]
Anyway. I can build it locally with the same docker image so I'm merging. We'll see if this is a transitory problem on GH side or what.

**Pull request merged**
