### PR TITLE
3 releases

### PR DESCRIPTION
**Pull request by pjljvandelaar**
Did I forget this?

### CODE REVIEW

**Comment by mosteo** [comment]
There seems to be a problem with some compiler versions:

`rejuvenation-utils.adb:4:18: warning: no entities of "GNATCOLL.GMP.Integers" are referenced [-gnatwu]`

**Comment by Fabien-Chouteau** [comment]
It's probably the GNATcoll crate that should get a restriction on GNAT versions.

**Comment by pjljvandelaar** [comment]
What is alire's best practice?
What is now the best way forward?

* Reject this pull request completely, and make new releases?
* Make a new release with the same release number (22.0.1)?
* Make a new release with an incremented number (22.0.2)?

**Comment by Fabien-Chouteau** [comment]
@pjljvandelaar I don't think you need to make a new release.

Something I missed before is that you are contributing to the `stable-1.1` branch of the index, but your project is made with Alire 1.2. You should open the pull request against the `stable-1.2` branch instead.

**Pull request closed without merging**
