### PR TITLE
Create globe_3d-2023.11.12.toml

### PR DESCRIPTION
**Pull request by zertovitch**

### CODE REVIEW

**Review by zertovitch — COMMENTED** [review]
Fixed directory of project file

**Comment by zertovitch** [comment]
The checker borks for some reason... At least the issue seems to be OS-neutral:
ALIRE.CHECKED_ERROR
Windows: Unexpected contents where a single directory was expected: D:\a\alire-index\alire-index\alr-cvqj.tmp
Ubuntu: Unexpected contents where a single directory was expected: /home/runner/work/alire-index/alire-index/alr-kvvp.tmp

**Comment by Fabien-Chouteau** [comment]
@zertovitch at the root of your tarball there should be only a directory with the sources in it. Here you have multiple files and directories at the root.

**Review by zertovitch — COMMENTED** [review]
New Zip file, new hash.

**Comment by zertovitch** [comment]
Looks definitely better!
Current state: Windows, Mac: OK, Linuxes: KO.
On Linuxes, Alire seems to build imported projects GID and Zip-Ada, but not to find them after that.

**Pull request closed without merging**
