### PR TITLE
Create gwindows-1.4.2.toml

### PR DESCRIPTION
**Pull request by zertovitch**

### CODE REVIEW

**Review by zertovitch — COMMENTED** [review]
GMGPL -> LGPL

**Review by zertovitch — COMMENTED** [review]
Zip ball uses the Zip 2.0 compression format (Deflate).

**Review by zertovitch — COMMENTED** [review]
Using a single root dir within Zip ball.

**Review by zertovitch — COMMENTED** [review]
Using Git (as in previous releases) instead of a Zip ball.
NB: the Alire test failure was something else (GNAT not found), but who knows...

**Review by zertovitch — COMMENTED** [review]
Removed extra GNATCOM tools path.

**Comment by zertovitch** [comment]
On Windows-Latest, the following error is issued:
`ERROR: Command ["gnat", "--version"] exited with code -1`

**Comment by Fabien-Chouteau** [comment]
There is another error before that:
```
stderr: Failed Outcome because of exception: 
stderr: file "C:\Users\runneradmin\AppData\Local\alire\settings\indexes\community\repo\.git\objects\pack\pack-9e939a97bf3f271e15e648601f39ab7d3be8f9cb.idx" could not be deleted
stderr: raised ADA.IO_EXCEPTIONS.USE_ERROR : file "C:\Users\runneradmin\AppData\Local\alire\settings\indexes\community\repo\.git\objects\pack\pack-9e939a97bf3f271e15e648601f39ab7d3be8f9cb.idx" could not be deleted
[D:\a\alire-index\alire-index\alire_install\bin\alr.exe]
```

I don't know if both are related.

The second issue is that there's no GNAT nor Gprbuild in PATH. I don't know why Alire is not adding them to the dependency tree,

**Review by mosteo — APPROVED** [review]

**Comment by mosteo** [comment]
The trouble was related to our `setup-alire` action due to a new path on Windows only, which I'm fixing now.

**Pull request merged**
