### PR TITLE
Create zipada-58.0.0.toml

### PR DESCRIPTION
**Pull request by zertovitch**
Moving on to Zip-Ada version 58.

### CODE REVIEW

**Comment by mosteo** [comment]
It seems linker switches for macOS are different: https://stackoverflow.com/a/24799865/761390

**Comment by zertovitch** [comment]
In commit https://github.com/zertovitch/zip-ada/commit/70f273aca89b859ab5dbd2969c85e0414b299d5b
I make the linker use `-dead_strip` for Mac (scenario variable Zip_OS = "MacOSX").
But how to relate that to values known to Alire, through `os=mac`?

**Comment by mosteo** [comment]
I see you found the way to use scenario variables.

In regard to [these warnings](https://github.com/alire-project/alire-index/runs/8050811060?check_suite_focus=true#step:9:565), maybe the Alire manifest requires updating to remove the not-built binaries?

**Comment by zertovitch** [comment]
Do you mean the compilation diagnostics with `zip-compress-deflate.adb:361:05: info: in instantiation ` etc. ?
It's "infos", not real warnings. If it's disturbing, I can hide them via `-gnatw.N`.

**Comment by mosteo** [comment]
Merged, thanks.

**Pull request merged**
