### PR TITLE
Add json

### PR DESCRIPTION
**Pull request by onox**

### CODE REVIEW

**Comment by onox** [comment]
@mosteo The checks seems to be stuck :raised_eyebrow:

**Comment by mosteo** [comment]
Yup, and since it didn't even start I cannot cancel/restart it. Can you please touch something in the file and push or rebase?

**Comment by onox** [comment]
That did the trick.

**Comment by mosteo** [comment]
Great, thanks.

**Review by mosteo — APPROVED** [review]

**Pull request merged**
