### PR TITLE
Add crate for Dynamo 1.3.0 (code generator)

### PR DESCRIPTION
**Pull request by stcarrez**

### CODE REVIEW

**Comment by mosteo** [comment]
It seems mariadb is a dependency?

**Comment by stcarrez** [comment]
> It seems mariadb is a dependency?

Yes, you're right. I'll submit a libmariadb crate and update dynamo.

**Comment by stcarrez** [comment]
> > It seems mariadb is a dependency?
> 
> Yes, you're right. I'll submit a libmariadb crate and update dynamo.

Now, the root issue comes from the `ado_mysql` library which should have a dependency to mariadb.
I'll submit an update of the `ado_mysql` crate when the libmariadb crate is integrated.

**Comment by mosteo** [comment]
Just ping me here once everything is ready so I don't temporarily forget about this one.

**Comment by stcarrez** [comment]
@mosteo since ado_mysql is now fixed with a dependency to libmariadb, it should work.

**Comment by mosteo** [comment]
This can't succeed for the same reason as #619: some preinstalled packages in the ubuntu VMs conflict with libmariadb, and `alr` won't uninstall them. Testing locally everything seems OK, so I'm merging.

**Pull request merged**
