### PR TITLE
AWS 23.0.0

### PR DESCRIPTION
**Pull request by Fabien-Chouteau**

### CODE REVIEW

**Review by reznikmm — COMMENTED** [review]
I would propose to avoid `make build install` and use project files to build. So users could enable SSL if needed

**Comment by Fabien-Chouteau** [comment]
If that works I am all for it.

**Comment by reznikmm** [comment]
> If that works I am all for it.

I'm trying [this](https://github.com/alire-project/alire-index/pull/687)

What is `gcc -dumpmachine` on Mac OS X?

**Comment by reznikmm** [comment]
can I select `gpr-set-externals` by compiler version? GNAT CE 2021 and alire GCC uses `TARGET=x86_64-pc-linux-gnu`, but system GCC uses `x86_64-linux-gnu`.

**Comment by mosteo** [comment]
> can I select `gpr-set-externals` by compiler version?

No, this is not supported at the moment. Only the variables listed under SYSTEM in `alr version`.

**Comment by reznikmm** [comment]
I've disabled all compilers except `gnat_native` to have a single `TARGET` per platform.

**Pull request closed without merging**
